alantech/alan

.github/workflows/tests.yml, bdd/spec/011_array_spec.sh, bdd/spec/021_trig_spec.sh, bdd/spec/022_deps_spec.sh, runtime/src/vm/opcode.rs
[![Return of the Mac](https://media1.tenor.com/images/ef218ae5347521e7faa00ebb40b8d1ad/tenor.gif?itemid=14581494)](https://open.spotify.com/album/6plavTFCGXv5vpy0jZVtOV?highlight=spotify:track:3jDdpx9PMlfMBS5tOBHFm9)
=> Restore MacOS CI testing

compiler/src/agatoagc.ts, compiler/src/ammtoaga.ts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number
=> safari does not recognize big int literal notation

bdd/spec/011_array_spec.sh, compiler/src/lntoamm/opcodes.ts, js-runtime/index.js, runtime/src/vm/memory.rs, runtime/src/vm/opcode.rs, std/root.ln
=> array pop working with new Result-based signature

bdd/spec/011_array_spec.sh, js-runtime/index.js, runtime/src/vm/opcode.rs
=> Every and Some

bdd/spec/011_array_spec.sh, compiler/src/lntoamm/Type.ts, compiler/src/lntoamm/opcodes.ts, js-runtime/index.js, runtime/src/vm/memory.rs, runtime/src/vm/opcode.rs, std/root.ln
The final PR to resolve \#80
Our opcode closure generation is very broken, though :(
=> Reduce, Filter, Concat

rfcs/008 - Safe Global Data Storage RFC.md
Forgot to update this before landing it.
=> Update 008 - Safe Global Data Storage RFC.md

compiler/src/agatoagc.ts, compiler/src/ammtoaga.ts, compiler/src/ammtojs.ts, compiler/src/index.ts, compiler/src/lntoamm/Ast.ts, compiler/src/lntoamm/Event.ts, compiler/src/lntoamm/Microstatement.ts, compiler/src/lntoamm/Module.ts, compiler/src/lntoamm/Statement.ts, compiler/src/lntoamm/Type.ts, compiler/src/lntoamm/UserFunction.ts
=> Eliminate process.exit from the compiler (except the CLI index file)

bdd/spec/012_hash_spec.sh, runtime/src/vm/memory.rs, runtime/src/vm/opcode.rs
Completely reworks registers to be pointers and closure memory as a nested HandlerMemory.
Resolves \#164
=> HashMap on main runtime

.github/workflows/tests.yml, bdd/spec/024_clone_spec.sh, compiler/src/ammtoaga.ts, compiler/src/lntoamm/UserFunction.ts, js-runtime/index.js, runtime/src/vm/opcode.rs, std/root.ln
=> Add a 'clone' function that works for all data types. Built by taking over the 'assign' function and fixing some bugs in it

bdd/spec/012_hash_spec.sh, compiler/src/lntoamm/Type.ts, js-runtime/index.js, runtime/src/vm/memory.rs, runtime/src/vm/opcode.rs, std/root.ln
=> Array of KeyVal pairs to HashMap converter function, useful for opcode interop

compiler/src/index.ts
=> Better compiler help message

bdd/spec/023_http_spec.sh, js-runtime/index.js, runtime/src/vm/memory.rs, runtime/src/vm/opcode.rs, runtime/src/vm/program.rs, runtime/src/vm/run.rs
Resolves \#233 and also cleans up the string manipulation logic in the opcodes.
=> Web server in rust runtime

bdd/spec/025_runtime_error_spec.sh, runtime/src/vm/run.rs
=> Better File-not-found error for the runtime

bdd/spec/003_math_spec.sh, compiler/package.json, compiler/src/lntoamm/Microstatement.ts, runtime/Cargo.toml
=> Fix bug with operator groups of one value

bdd/spec/026_datastore_spec.sh, compiler/package.json, compiler/src/lntoamm/opcodes.ts, compiler/yarn.lock, js-runtime/index.js, js-runtime/package.json, rfcs/008 - Safe Global Data Storage RFC.md, std/datastore.ln
Beginning to implement RFC 008
Part 1 of 2 for #238
=> @std/datastore (js-runtime only for now)

bdd/spec/001_event_spec.sh, compiler/package.json, compiler/src/agatoagc.ts, compiler/src/ammtoaga.ts
=> Fix issue when no global memory is present in the compiled output

.github/workflows/release.yml
I unfortunately can't test this until it is landed but here it is for a quick review. The rest of the work will be directly committing to main, making tags, and seeing if it works or not.
=> Automatic release generation

bdd/bdd.sh, bdd/spec/018_closure_spec.sh, compiler/src/lntoamm/Microstatement.ts, js-runtime/index.js
Actually foundational work that's needed for both \#194 and \#195
=> Get closure function by reference (barely) working, also make test suite use the right 'alan' binary when one is already in the PATH

README.md
Always link to the latest release instead of a fixed one.
=> Update download link in readme

bdd/spec/011_array_spec.sh, bdd/spec/018_closure_spec.sh, compiler/src/lntoamm/Microstatement.ts, compiler/src/lntoamm/StatementType.ts, compiler/src/lntoamm/UserFunction.ts, compiler/src/lntoamm/opcodes.ts
Resolves #194 and resolves #195 simultaneously. Wasn't able to cleanly separate them when I actually dug into it.
=> Lazily and multiple-y dispatched closure functions

avm/src/benchmark/run.rs, avm/src/vm/memory.rs, avm/src/vm/opcode.rs, avm/src/vm/program.rs
Currently very broken, but it's hit midnight and that's when I decided to call it. Will continue tomorrow after an appointment.
=> Redo the AVM memory model

avm/src/vm/memory.rs, avm/src/vm/opcode.rs, bdd/spec/027_seq_spec.sh, compiler/src/ammtoaga.ts, rfcs/007 - Sequential Algorithms RFC.md, rfcs/009 - Tree RFC.md
=> Implement @std/seq's recurse functionality in the AVM

avm/src/vm/memory.rs, avm/src/vm/opcode.rs, bdd/spec/027_seq_spec.sh, compiler/src/ammtoaga.ts
=> Fix two recursion bugs, one in the selfrec opcode and one in the ammtoaga layer of the compiler

bdd/spec/011_array_spec.sh, compiler/src/lntoamm/UserFunction.ts, std/root.ln
I was not able to reproduce the issue pointed out by @MareinK. Will need to ask what the difference
is with this and what was tried before.
=> Add Orderable interface, use to simplify min/max implementation.

bdd/spec/011_array_spec.sh, compiler/src/lntoamm/opcodes.ts
Resolves \#340
Thanks to @ledwards for pointing this out!
=> Fix bug with find closure return type

avm/src/vm/opcode.rs
Thanks to @cdmistman for spotting this!
=> Fix the findl opcode when mutating outer scope

bdd/spec/009_conditional_spec.sh, compiler/src/lntoamm/Ast.ts, compiler/src/lntoamm/Microstatement.ts
=> Fix conditional let reassignment

rfcs/011 - Function Type RFC.md
=> Function Type RFC

bdd/spec/012_hash_spec.sh, std/root.ln
=> Fix double-assignment bug in HashMap

bdd/spec/031_module_import_spec.sh, compiler/src/ln.ts
=> Fix issue with trailing whitespace in import lines causing parse errors

rfcs/013 - Datastore Revisited RFC.md
This is now ready for review :)
=> Datastore Revisited RFC

README.md
dropping ANTLR ungated Node, upgrading to Tokio 1.0 bumped the minimum Rust version
=> Update source build deps

bdd/spec/032_json_spec.sh, js-runtime/index.js, std/json.ln, std/root.ln
Works for both the js-runtime and AVM now!
=> Get complex JSON API creation and serialization working

avm/.gitattributes, avm/Cargo.lock, avm/Cargo.toml, avm/src/daemon/daemon.rs, avm/src/daemon/dns.rs, avm/src/daemon/lrh.rs, avm/src/daemon/mod.rs, avm/src/main.rs, avm/src/vm/deploy.rs, avm/src/vm/opcode.rs
Missing actually sending system stats to finish CLI part of autoscalable alan deploy
=> Get peers from DNS and determine leader

avm/src/daemon/mod.rs
=> Fix daemon mode

avm/src/vm/opcode.rs, bdd/spec/023_http_spec.sh, compiler/src/lntoamm/Type.ts, js-runtime/index.js, std/http.ln
This was easier than I expected
=> Expose the HTTP 'method' on server calls

avm/src/vm/opcode.rs
This resolves \#443 and big thanks to @cdmistman for the help on getting this done so quickly!
=> Don't hang HTTPS server when TLS handshake fails

avm/src/main.rs
=> Add deploy --app-id option

avm/src/main.rs
Fixes: https://github.com/alantech/meta/issues/164
=> Pin alan version

avm/src/vm/http.rs, avm/src/vm/mod.rs, avm/src/vm/opcode.rs, avm/src/vm/program.rs, avm/src/vm/run.rs
Almost done with this, but I don't know how to make Rust happy with the types that were automatically resolved before.
=> AVM Http refactoring WIP

Makefile, avm/src/vm/opcode.rs, bdd/spec/015_maybe_result_either_spec.sh, compiler/src/ammtoaga/depgraph.ts, compiler/src/lntoamm/Microstatement.ts, compiler/src/lntoamm/opcodes.ts, js-runtime/index.js, std/root.ln
=> More Stringifiable Definitions

anycloud/cli/src/deploy/mod.rs
This will allow handling unsupported CLI version errors
=> pass the cli version on every request

avm/src/daemon/daemon.rs
Currently taking about 16 minutes
```
2021-04-15T21:52:06.940711+00:00 app[web.1]: 2021-04-15T21:52:06.940Z | INFO | staging | POST /stats 200
2021-04-15T22:07:59.214060+00:00 app[web.1]: 2021-04-15T22:07:59.213Z | INFO | staging | POST /stats 200
```
=> go back to a ~5m period to send stats

anycloud/cli/src/deploy/mod.rs, anycloud/cli/src/logger/mod.rs, anycloud/cli/src/main.rs, anycloud/cli/src/oauth/mod.rs
paired with: https://github.com/alantech/deploy/pull/86
=> Add warn macro and set every user fault a warning

avm/Cargo.lock, avm/Cargo.toml
Updating protobuf dependencies since main repo has been updated. https://github.com/stepancheg/rust-protobuf/pull/553#issuecomment-826452227
=> Update proto dependencies

anycloud/cli/src/deploy/mod.rs
Related issue: https://github.com/alantech/meta/issues/183
Related PRs:
- https://github.com/alantech/alan/pull/506
- https://github.com/alantech/deploy/pull/98
=> Optional vm type and region

anycloud/cli/Cargo.lock, anycloud/cli/Cargo.toml, avm/Cargo.lock, avm/Cargo.toml, avm/src/daemon/ctrl.rs, avm/src/daemon/daemon.rs, avm/src/daemon/dns.rs, avm/src/daemon/stats.rs, avm/src/vm/memory.rs, avm/src/vm/opcode.rs, compiler/package.json, js-runtime/package.json
Still a WIP, but all of the necessary pieces have now been built. Planned perf improvements in a followup PR.
=> Distributed Datastore

avm/Cargo.toml, avm/src/daemon/stats.rs
Got tired of ssh'ing into an x86 box any time I'm on my PineBook Pro...
=> Get the AVM compiling on ARM again

anycloud/docs/how-to/aws-postgres.md
For easier review https://github.com/alantech/alan/blob/psql/anycloud/docs/how-to/aws-postgres.md
=> improvements to how-to aws psql prisma guide

anycloud/cli/src/oauth/mod.rs
Thanks @cdmistman for spotting this.
=> Fix a bug in the first-time usage of 'anycloud' introduced with authentication

anycloud/docs/install.md
Thanks to alwye in the Anycloud Discord!
=> Fix the published artifacts link in the anycloud documentation

avm/src/daemon/ctrl.rs
Resolves \#560.
The issue is it load balancing the request into :443 instead of :4142, but also, we should not load balance these requests at all, as they are intentionally meant to be for direct communication to that particular AVM instance (either from the deploy service to get metadata about the exact node it connected to, or for the server in the Docker container in AnyCloud usage to get low-latency communication to its AVM sidecar process).
So simply deleting the load balancing entirely for :4142 should resolve the strange behaviors noted by @aguillenv :)
=> Remove the broken load balancing on the control port

anycloud/cli/src/deploy/mod.rs
@cdmistman Please take a look and let me know if this change makes sense or do you think is related to another part of the flow.
The error is the following when executing `new` or `terminate`:
```rs
thread 'main' panicked at 'attempt to subtract with overflow', /Users/alejandro/Documents/projects/alantech/alan/anycloud/cli/src/deploy/mod.rs:1321:44
```
=> Add lines length check

anycloud/cli/alan/anycloud.ln, anycloud/node/src/datastore.ts
Fixes: #580 
It works for me locally on macOS:
and everything keeps working:
=> Fix docker connection to host

avm/Cargo.lock, avm/Cargo.toml, avm/src/main.rs
Two major versions in between. Sticking to the builder style since that required less refactoring
=> Switch to the latest version of clap

avm/Cargo.lock, avm/Cargo.toml, avm/src/cloud/common/mod.rs, avm/src/compile.rs
It was apparently deprecated years ago
=> Migrate off tempdir

src/compile.rs, src/std/root.ln, src/std/root.rs
Proper support for generic types will be necessary before further progress can happen here (except if I want to create a bazillion bindings to the `getOrExit`
=> Implement simple i8 arithmetic.

src/lntors/typen.rs, src/parse.rs, src/program.rs
and also a minor cleanup of statement_to_microstatements,
=> Eliminate all compiler warnings

src/compile.rs, src/lntors/event.rs, src/lntors/function.rs, src/parse.rs, src/program.rs, src/std/root.ln, src/std/root.rs
testing with i64 math, and fix formatting,
=> Implement operator support

src/compile.rs, src/parse.rs, src/program.rs
Still a hacky approach, but I need this working for something else that I'm working on.
=> Get 'var.fnname()' method syntax working

src/compile.rs, src/std/root.ln, src/std/root.rs
The way this is done is definitely not long-term, just getting to a demo-able point to show GPGPU perf possibilities.
=> Add basic Vec support

.github/workflows/bench.yml, benches/bench.ln, src/compile.rs
=> Turn on optimization

src/compile.rs, src/std/root.ln, src/std/root.rs
Adding bindings and functions for buffer creation and reading from buffers. I'm starting to feel the restrictions this half-baked compilation layer is imposing on me, though.
Tomorrow I'll work on updating the benchmark to use this form. I don't expect it to be any faster than perhaps even the linear scan due to the extra memcpys involved, but I might be surprised.
After that I'll be going deep on syntax (both changes in syntax between Alan v0.1 and v0.2) as well as just implementing syntax that's currently broken (looking at you, conditionals and generics).
But definitely excited about this change :)
=> Real GPGPU

src/compile.rs
This resolves #688 and prevents two issues I noticed while manually compiling the benchmark file:
1. If you change the set of dependencies an Alan project uses, it wouldn't show up without completely blowing away the build directory.
2. If you get a failure to build but have a working executable already in the cache, it will return that binary to you, which can be very confusing if the last thing you compiled was the same project but with some edits. This was covered up by the test suite never doing that *and* the expected outputs of the binaries being different from each other.
=> Always write out the  file and always delete the generated binary before the build

src/parse.rs, src/program.rs
I realized that a lot of the maintenance burden with the baseassignablelist parsing function was that the method separator (`.`) was part of the *variable* rather than another element in the baseassignablelist, which significantly complicated any attempts at turning the it into a state machine. Swapping it over has bloated the code a bit, but I have more branches in the code implemented, as well, and fewer weird hacks.
=> Rewrite the baseassignablelist parsing

benches/map.rs, src/compile.rs, src/lntors/function.rs, src/lntors/mod.rs, src/lntors/typen.rs, src/main.rs, src/parse.rs, src/program.rs
I haven't run `cargo fmt` in a while. Maybe I should make that a gh actions check
=> Run cargo fmt

.github/workflows/rust.yml, src/main.rs
Adding a new check for formatting mistakes, and also testing that it works in this PR (the last commit will be reverted before merging)
=> Add a formatting check to github actions

src/compile.rs, src/std/root.ln, src/std/root.rs
Not hard, and probably not necessary at the moment, but it was just bothering me being ~80% implemented instead of 100%
=> Fill out the integer implementation

src/lntors/typen.rs, src/parse.rs, src/std/root.ln
This PR is focused on the syntax parsing side of things, and partially moves to the new type system. Actually implementing the `ctype`s and reworking the function syntax to wrap around a type declaration is the next step
=> Expand the type syntax to be more function-like

src/compile.rs, src/std/root.ln, src/std/root.rs
Simple PR to implement the comparison operators
=> Implement the comparison operators

src/program.rs
This doesn't actually use them, yet, but I wanted to stop here before I start using them, as the part that actually uses them is going to have to replace the current way types are handled in the compiler, and should be considered separately.
=> Implement the built-in type functions

.github/workflows/rust.yml, Cargo.lock, src/compile.rs
Updating the lockfile from time-to-time to try and prevent bitrot. May want to do the same thing in the compile path.
=> Update the lockfile

src/program.rs
The only not-yet-implemented CTypes after this PR are the Generic-related types.
This only implements the parsing of the Alan code into the nom tree and from there into the CType tree. It doesn't implement the serialization of these types into Rust (since they aren't being tested, yet). That will be a follow-up PR.
=> Implement more CTypes

src/program.rs
I noticed a couple of minor things I forgot to clean up on the last PR after I merged it, so just getting that fixed.
=> Some minor fixes

src/compile.rs, src/lntors/function.rs, src/lntors/typen.rs, src/program.rs, src/std/root.ln, src/std/root.rs
I knew since I didn't test a lot of it that there would be bugs, but this was a bit more than I expected. It's kinda wild how it was able to work at all prior to this change.
=> Implement 'Either{A, B}'

Cargo.lock, src/compile.rs, src/lntors/function.rs, src/lntors/typen.rs, src/parse.rs, src/program.rs, src/std/root.ln, src/std/root.rs
I completely reworked how the baseassignmentlist is parsed, which let me add features while *reducing* LOC, which is always great. :)
And I wasn't even focused on LOC minimization, I think there are some places I could further reduce things.
=> Implement lazy type generation and constructor function calling, and array literal syntax (both creation and accessor syntax)

.github/workflows/bench.yml, .github/workflows/release.yml, .github/workflows/rust.yml
The github actions UI shows a deprecation notice, so this PR attempts to fix it.
=> Update github checkout version

src/compile.rs, src/program.rs, src/std/root.ln, src/std/root.rs
This is a small set of tests that were easy wins to get over the line, since my mind is a bit fried from the `wgpu` debugging debacle.
=> Get some more tests passing

Cargo.lock, src/compile.rs
I tested this in a VM, so I was unable to test/fix anything GPU-related, but everything else now works.
I guess I need to build a cheap Windows box to go any further :/
=> Fix things on Windows

src/compile.rs, src/lntors/function.rs, src/program/constn.rs, src/program/ctype.rs, src/program/function.rs, src/program/microstatement.rs, src/program/operatormapping.rs, src/program/program.rs, src/program/scope.rs, src/program/typeoperatormapping.rs, src/std/root.rs
Add support to all top-level types for conditional compilation (which will be immediately used for built-in testing support).
This PR also fixes a few bugs that were discovered in the process of writing it.
Resolves #758
=> Implement conditional compilation

benches/bench.ln, src/program/ctype.rs, src/program/program.rs, src/std/root.ln
In the process I found a few more places where the constructor and accessor functions wouldn't be properly created (one of them blocking the benchmarks) so I fixed that at the same time.
=> Drop the Vec type from Alan

src/compile/integration_tests.rs, src/std/root.ln, src/std/root.rs
Super easy to do this one, which is very promising. :) I'm debating on the order of the arguments for the second reduce, though. I don't know why but this order feels "off."
=> Implement reduce for buffers

src/compile/integration_tests.rs, src/std/root.ln, src/std/root.rs
And also the generic `getOr` functions for `Maybe` and `Fallible`.
=> Implement the array and buffer find function

src/compile/integration_tests.rs, src/program/microstatement.rs, src/program/operatormapping.rs, src/std/root.ln
This was an Alan v0.2 blocker, but I forgot to create an issue for it.
=> Redo operator mapping and get variable negation working

src/program/scope.rs
Fixes some clippy issues that apparently didn't block the PR last night.
=> Clippy fixes

src/compile/integration_tests.rs, src/std/root.ln, src/std/root.rs
Resolves #750 and resolves #790
=> Implement the `Array` `store` and `delete` functions and the `Buffer` `store` function

src/compile/integration_tests.rs
Just going through ignored tests and seeing which ones can be brought back.
=> Revive the main Maybe test

src/compile/integration_tests.rs
This test may or may not be useful. After it passes, I'm going to see if I've got full coverage of what it tests in the other tests I wrote.
=> Remove the Dict support test

src/std/root.ln
=> More GPU Vector accessor functions

src/std/root.ln
=> Apparently these combined property accessors can also access values to rearrange them

src/compile/integration_tests.rs, src/std/root.ln, src/std/root.rs
=> addChild accepts a Tree as a new node

src/std/root.ln
=> Implement the GPGPU boolean and bitwise operations

src/std/root.ln
=> Implement GPU bitcast functionality

src/std/root.ln
=> GPU Vector functions

src/program/ctype.rs, src/program/scope.rs, src/std/root.ln, src/std/root.rs
This is not *yet* net-negative, but as time goes on it will be less overall code.
=> Add Infix and Prefix native operator binding support and implement some i8 functions as native op bindings

src/compile/integration_tests.rs, src/program/function.rs, src/program/microstatement.rs, src/std/root.ln
Now that looks much nicer, especially for closure functions. :)
=> Drop the arrow in most situations

alan/src/compile/integration_tests.rs, alan/src/compile/mod.rs, alan/src/lntojs/function.rs, alan/src/lntojs/mod.rs, alan/src/std/root.ln
Also get a few more tests running in both JS and Rust and adjust string serialization to not create multi-line strings (which don't exist in JS)
=> Actually get the js std import working

alan/src/compile/integration_tests.rs, alan/src/std/root.ln
Also switch to a notU8/notU16 function instead of the weird hack in the root scope.
=> Bind the js u16 bitwise and arithmetic operations

alan/src/compile/integration_tests.rs, alan/src/lntojs/function.rs, alan/src/program/ctype.rs, alan/src/std/root.ln
I also discovered some bugs along the way. Some were easy and fixed, but I just worked around a scope bug with inner functions aliasing outer function types for now.
=> Get a few more js tests working

alan/src/compile/integration_tests.rs, alan/src/compile/mod.rs, alan/src/lntojs/function.rs, alan/src/lntojs/mod.rs, alan/src/std/root.ln
All of this work to get `wait` working in JS-land.
I wouldn't mind the function colors *that* much if there weren't certain features locked behind them. Rust has function colors, as well, but it's *possible* to replicate the same functionality with normal functions. Not so in JS.
=> JS function colors suck

alan/src/compile/integration_tests.rs, alan/src/std/root.ln
After the last few large PRs, this is now relatively simple in comparison.
=> Get mutable functions working in JS

alan/src/compile/integration_tests.rs, alan/src/program/ctype.rs, alan/src/program/program.rs, alan/src/std/root.ln
Also finally add a test macro for multi-file tests and use it for this test.
=> Implement importing types from other files

alan/src/compile/integration_tests.rs, alan/src/compile/mod.rs, alan/src/lntojs/function.rs, alan/src/lntojs/mod.rs, alan/src/lntors/function.rs, alan/src/lntors/mod.rs, alan/src/program/ctype.rs, alan/src/program/function.rs, alan/src/program/microstatement.rs, alan/src/program/program.rs, alan/src/program/scope.rs
This required a wider-ranging refactor than I expected. I'm not super excited about the changes to the `Program`, but it's working!
=> Get basic function imports working

alan_std.js, alan_std.test_gpgpu.js, alan_std/src/lib.rs
Because of reasons with monorepo weirdness in both Rust and JS, I need to merge these things first. It will break the compiler temporarily. :/
=> Generalize GPU buffer create/read/update. Part 1

alan/src/compile/integration_tests.rs, alan/src/program/ctype.rs, alan/src/program/microstatement.rs, alan/src/program/scope.rs
This implementation is hacky at the moment, so I'm not sure how well it'll work, but it does pass with the provided test case.
=> Allow calling higher-order generic functions with a generic function as the argument

alan/src/lntors/mod.rs, alan/src/std/root.ln
No test for this, as a follow-up PR will be porting most of the integration tests into this framework.
However, I do have [a quick demo](https://techhub.social/@ISV_Damocles/113512131879820175) of the framework in action in both JS and Rust.
=> An initial testing framework for Alan

alan/src/compile/mod.rs
I originally wrote this while working on GPU rendering support, but I'm needing it across multiple branches, now, so I'm pulling this change out as a separate PR.
=> Branch support for Cargo git deps

alan/src/program/ctype.rs, alan/src/std/root.ln, alan/test.ln, alan_std.js, alan_std/src/lib.rs
- **wip**
- **Add js async sort function**
- **Bind and test the new sort functions**
=> Implement the `sort` functions

alan/src/program/ctype.rs, alan/src/std/root.ln
I accidentally left this in before merging the last PR
=> Remove the test branch from the root scope

alan/src/compile/integration_tests.rs, alan/src/lntojs/typen.rs, alan/src/lntors/function.rs, alan/src/lntors/typen.rs, alan/src/program/microstatement.rs, alan/src/std/seq.ln
(Also delete a block of code that I figured out was a useless vestige that does nothing but mutated itself in enough ways to get through the dead code check)
=> Implement `@std/seq` `iter` and make mutable closure functions to do it

alan/src/std/root.ln, alan/test.ln, alan_std.js
- **Implement Javascript bitcasting functions**
- **I didn't quite get what the length value was meant to be. It looks like I can elide it in my usage, though.**
- **Bind the bitcasting functions and implement the bitpacking and unpacking functions (for both wgsl and CPU equivalents**
=> Bitcasting and Bitpacking/unpacking

alan/src/compile/integration_tests.rs, alan/src/std/root.ln, alan/test.ln, alan_std.js, alan_std.test.js
- **Implement reverseBits method in JS**
- **Implement and test reverseBits for the CPU**
- **Add GPGPU test**
=> `reverseBits`

alan/src/compile/integration_tests.rs, alan/src/std/root.ln, alan/test.ln, alan_std.js, alan_std.test.js
- **Implement `roundTiesEven` method in JS**
- **Implement bindings and tests for CPU and GPU round**
=> Implement `round`

alan_compiler/src/lntojs/function.rs, alan_compiler/src/lntojs/mod.rs, alan_compiler/src/lntojs/typen.rs, alan_compiler/src/lntors/function.rs, alan_compiler/src/lntors/typen.rs, alan_compiler/src/program/constn.rs, alan_compiler/src/program/ctype.rs, alan_compiler/src/program/fnkind.rs, alan_compiler/src/program/function.rs, alan_compiler/src/program/microstatement.rs, alan_compiler/src/program/operatormapping.rs, alan_compiler/src/program/scope.rs, alan_compiler/src/program/typeoperatormapping.rs
This produced a massive performance win, getting the `Hello, World` down to less than a second!
=> Convert `CType` to be based on `Arc` instead of `Box`

alan/src/compile/integration_tests.rs, alan_compiler/src/std/root.ln, alan_std.js
I nearly convinced myself there was a bug in Naga while working on this...
=> Implement `transpose`

Cargo.lock, alan_compiler/Cargo.toml, alan_compiler/src/lntojs/function.rs, alan_compiler/src/lntojs/typen.rs, alan_compiler/src/lntors/function.rs, alan_compiler/src/lntors/typen.rs, alan_compiler/src/program/ctype.rs, alan_compiler/src/program/function.rs, alan_compiler/src/program/microstatement.rs, alan_compiler/src/program/scope.rs
- **wip**
- **Implement weakmaps for all three major string genrating type functions and refactor more things to pass Arc<CType> around to actually realize a performance boost**
=> Implement WeakMaps for all three major string generating type functions and refactor more things to pass Arc<CType> around

alan/src/compile/integration_tests.rs, alan_compiler/src/std/root.ln
This is only a PR for formality's sake. I don't expect any issues. While talking to others about Alan, I realized a couple of minor things that could be improved, so I improved them.
=> Minor improvements to a couple pieces of code

alan/src/compile/integration_tests.rs, alan_compiler/src/lntojs/function.rs, alan_compiler/src/lntojs/typen.rs, alan_compiler/src/program/ctype.rs, alan_compiler/src/program/scope.rs, alan_compiler/src/std/root.ln, alan_std.js
- **Refactor GBuffer to eliminate a lot of weird typing issues**
- **Delete commented out code from root scope**
- **Expand the hack in the JS FuzzySet, for now**
- **Accidentally pushed before saving all of the changes**
- **Modify the readBuffer method in JS**
- **Move to regex for figuring out the type, I forgot how long the type strings are in JS**
- **Fix up issues with the JS-path in the compiler revealed by this refactoring**
=> Refactor `GBuffer`
