alantech/alan

- runtime/src/vm/memory.rs
This was originally going to also include the refactoring of the 'resfrom' opcode, but I decided it's a big enough and complex enough change that it should stand on its own right. Supports work for \#164
> Convert registers from tree traversal to pointers

- .envcheck.sh
- .semver.js
- Makefile
Resolves \#186 found by @Raynos
@depombo can you pull this branch locally and confirm that you can still `make clean && make bdd` on a Mac? While the OSX CI tests will *probably* pick up any issues, I would like a confirmation on genuine hardware ;)
> Add an environment check at the beginning of make build to avoid misleading problems on build issues

- Makefile
- bdd/spec/023_http_spec.sh
- bdd/spec/027_seq_spec.sh
- compiler/package.json
- compiler/src/ammtojs.ts
- compiler/src/lntoamm/Microstatement.ts
- compiler/src/lntoamm/Type.ts
- compiler/src/lntoamm/UserFunction.ts
- compiler/src/lntoamm/opcodes.ts
- compiler/yarn.lock
- js-runtime/index.js
- js-runtime/package.json
- rfcs/007 - Sequential Algorithms RFC.md
- runtime/Cargo.lock
- runtime/Cargo.toml
- runtime/src/vm/opcode.rs
- std/seq.ln
Working so far:
* js-runtime
* seq
* next
* each
* while
* doWhile
* recurse
* AVM
* seq
* next
* each
* while
* doWhile
Not yet working:
* js-runtime
* generator
* AVM
* recurse
* generator
Fixed some bugs with conditional rewriting and closure generation that fixed `recurse` and probably a lot of other uses of closure functions. But I know the AVM still has the hard limit on closures (besides `condfn` closures) being a single fragment so there needs to be a follow-up PR to fix that before `recurse` can be implemented for the AVM.
> Implement most of @std/seq

- bdd/spec/019_compiler_error_spec.sh
- compiler/src/lntoamm/Module.ts
- compiler/src/lntoamm/Scope.ts
Thanks to @LoPoHa for finding this bug! Resolves \#283
Creates a new `shallowGet` function for the Scope object to explicitly only get a value if it's in that exact scope, and not in the scope chain (the export scope has the unexported scope within its chain so exported functions still work).
> Fix importing unexpected values

- std/root.ln
While digging in on why the Tree implementation isn't working in the AVM, I discovered that the implementation's `getChildren` and most complex `addChild` functions were incorrect and it wasn't caught by the test suite because Javascript's type coercion of `undefined` to `false` masked the issue.
One more reason why we have two targets right now, makes finding this stuff easier. :)
There are definite compiler glitches in the ammtoaga layer, though, that I'll be targeting next.
> Fixes to the Tree implementation

- compiler/src/ammtoaga.ts
This makes the Tree code correctly compile for the AVM and output *something.* The next change is to the AVM itself to do less copying and more referencing of existing data.
> Fix return statements in one of the branches for closures in the ammtoaga layer

- bdd/spec/011_array_spec.sh
I haven't been good about adding regression tests for several of the bugfixes that I've been tackling, but this one is too important to ever regress on, so I'm explicitly adding it here.
> Add a test confirming that user-defined types in array methods work

- avm/src/vm/opcode.rs
- bdd/spec/030_cmd_spec.sh
Our usage of `exec` in `@std/deps` was not complete enough to catch this as only the status code is apparently used?
Thanks to @MareinK for finding this and providing a great test application. :)
> Fix the execop implementation in the AVM

- bdd/spec/027_seq_spec.sh
- compiler/src/lntoamm/Microstatement.ts
- compiler/src/lntoamm/Statement.ts
- compiler/src/lntoamm/UserFunction.ts
Resolves \#315 by making one-liner functions more like "normal" functions after the AST parsing.
> Fix type inference for one-liner functions with method syntax

- bdd/spec/025_runtime_error_spec.sh
- std/root.ln
After see @ledwards' advent of code submissions, realized that this option is missing for CLI-type applications that really do want to halt on error instead of continuing. Providing a default value that is completely nonsensical will just produce nonsensical outputs.
> getOrExit function

- bdd/spec/023_http_spec.sh
- compiler/src/lntoamm/Module.ts
- compiler/src/lntoamm/UserFunction.ts
Thanks to @ledwards for finding this with this example file: https://gist.github.com/ledwards/1b1497d0e53875a59054c4e36879bab0
`from` imports were obliterating any functions and operators with the same name within the scope before. This merges it (with the imported functions getting precedence on checking) similar to how defining new functions and operators within the scope merges them in the scope.
Will update this PR shortly with an even simpler test case. This might break a test on error reporting because I made the reporting better for not-found functions.
> Merge function and operator from imports with existing functions and operators with the same name within the module

- avm/src/vm/event.rs
- avm/src/vm/memory.rs
- avm/src/vm/opcode.rs
- avm/src/vm/telemetry.rs
Example code from @ledwards demonstrated a couple of pathological cases in the AVM:
1. When dropping a value that is an array of nested arrays, the nested arrays stay around until the handler completes in a semi-detached state, so code that causes that in a tight loop can quickly OOM the AVM.
2. Many opcodes are needlessly `clone`-ing the handler memory data structure for convenience, putting `memcpy`s in a tight loop; coupled with (1) that means each iteration of the loop takes longer than the last.
On my machine, this makes an explicitly linear version of the example code to go from >2 hours runtime (I just killed it after it had been running that long) to ~1 minute. However, transpiling to Javascript and running it takes ~4 seconds, so there's still a ways to go.
Breaking this up into …
> AVM Perf Cleanup Part 1

- avm/src/vm/opcode.rs
- bdd/spec/006_string_spec.sh
Thanks to @ledwards for spotting this!
Proof that this test fails on current main:
```
Running: /bin/bash [bash 5.0.17(1)-release]
...Fpp
Examples:
1) Strings equality between global constant and 'live' string works runs agc
When run test_agc
1.1) The output should eq true
expected: "true"
got: "false"
\# /usr/local/alancorp/alan/bdd/spec/006_string_spec.sh:102
```
> AVM string equality fix for global strings

- FAQ.md
- Makefile
- compiler/package.json
Resolves \#347 and eliminates Python 2 from our build process!
> Use pkg instead of nexe

- bdd/spec/007_comparator_spec.sh
- std/root.ln
I'm not sure if this is the best way to do it. I couldn't find a way to simply do `toFloat = toFloat64`. Let me know if there is an easier way! I didn't add tests because there were no tests for the existing coercion functions.
> add toInt and toFloat type coercion aliases

- avm/src/vm/memory.rs
- avm/src/vm/opcode.rs
preliminary PR that tries to reinforce the memory abstraction by making opcodes as unaware as possible of how memory indices works. This sets the field for the next PR which will solve https://github.com/alantech/alan/issues/356 and hopefully require very little to no changes to `opcode.rs`
> Trim and refactor the AVM's fractal memory abstraction

- compiler/cypress/integration/bundle_check.js
- compiler/package.json
- compiler/yarn.lock
Originally was going to delete it entirely, but I forgot that the cypress tests also use it, so swapped to a different server that doesn't have the security vulnerability
> Jettison http-server for static-server

- avm/src/vm/event.rs
- avm/src/vm/instruction.rs
- avm/src/vm/opcode.rs
Changes all of the opcode native functions to be static functions instead of closures, also changes the implementation of the opcode macros.
> Opcode refactor

- avm/src/vm/event.rs
- avm/src/vm/opcode.rs
- avm/src/vm/run.rs
Proper event parallelism. It also no longer spins up one tokio task/greenthread per array element which fixes https://github.com/alantech/alan/issues/343 even without needing to batch parallel array methods
> Proper event parallelism

- .github/workflows/tests.yml
- bdd/spec/028_tree_spec.sh
- js-runtime/index.js
- std/root.ln
This was broken out from the JSON work because it became beefy enough as it is, and it could be useful now. It also fixes a bug in the js-runtime that wasn't caught until now.
> Add `toSubtree` method, and make fixes to the `addChild` functions to properly handle Trees and Nodes attached to other Trees

- avm/src/daemon/linux.rs
- pass in cluster id when posting stats 
- remove alan version which is readily available via DNS given the cluster id
- pick a new leader when the cluster size changes
> Listen on cluster size changes to determine cluster leader

- avm/Cargo.lock
- avm/Cargo.toml
- avm/src/vm/opcode.rs
- avm/src/vm/telemetry.rs
- bdd/spec/023_http_spec.sh
This doesn't add HTTPS support, but sets us up for it, since [hyper-rustls](https://github.com/ctz/hyper-rustls/blob/master/examples/server.rs) has server support, but [hyper-tls](https://github.com/hyperium/hyper-tls/tree/master/examples) apparently does not.
> Switch to rustls for hyper in the AVM

- avm/src/vm/event.rs
- avm/src/vm/opcode.rs
- avm/src/vm/program.rs
- avm/src/vm/run.rs
- bdd/spec/023_http_spec.sh
- compiler/src/ammtojs.ts
- compiler/src/lntoamm/opcodes.ts
- js-runtime/index.js
- std/http.ln
- std/httpserver.ln
Had to split the http client from the server because the `__conn` event handler is auto-attached when importing and that handler was being used to determine whether or not the http server should be started or not, but it now works as intended, and we can make it switch to HTTPS in the daemon with the appropriate PEM file being handed to it in a follow-up PR. :)
> Remove the http listen opcode (from users) and auto-listen on 80 or 8000 depending on context

- avm/src/daemon/linux.rs
- avm/src/daemon/nonlinux.rs
- avm/src/main.rs
The `alan daemon` stop using the hardcoded `anycloudapp.com` value and use the provided domain with its dns client.
> Add daemon domain argument

- avm/Cargo.lock
- avm/Cargo.toml
- avm/src/daemon/linux.rs
- avm/src/daemon/nonlinux.rs
- avm/src/main.rs
- avm/src/vm/opcode.rs
- avm/src/vm/program.rs
- avm/src/vm/run.rs
If you provide base64-encoded PEM files for a private key and a certificate to the alan daemon, it will switch the HTTP server to port 443 and use the cert and private key to run an HTTPS server.
> HTTPS Server support in alan daemon

- avm/src/vm/run.rs
Breaking this up into multiple PRs. The next one will be in the deploy service to make 4142 public and start using it for pinging, then a PR to add accepting an optional secret token to the AVM, then to get the deploy service to use that, then making it non-optional as the last PR for the initial version of the control port.
> Add the control port v0 implementation

- avm/src/vm/opcode.rs
- bdd/spec/023_http_spec.sh
- js-runtime/index.js
- std/httpserver.ln
This fixes half of \#463. The other half is a memory leak if `send` is *never* called, but that will require a much more clever solution to tackle.
> Fix double-calling `send` on an http server from crashing the AVM and js-runtime

- bdd/spec/033_tcp_spec.sh
- compiler/src/ammtojs.ts
- compiler/src/lntoamm/Type.ts
- compiler/src/lntoamm/opcodes.ts
- js-runtime/index.js
- rfcs/015 - TCP RFC.md
- std/tcp.ln
- std/tcpserver.ln
Needed to add a `ready` function to get it working as desired. Glad it was caught by the js-runtime since I think the AVM is even more vulnerable to this problem.
> Implement @std/tcp for the js-runtime

- anycloud/cli/src/main.rs
- anycloud/docs/reference/cli-api.md
- avm/src/main.rs
now top-level `app` cli commands and `credential`/`config` only differ in the nomenclature for editing them which is `upgrade` and `edit` respectively
> more consistent cli api naming proposal

- Makefile
Someone running `make && sudo make install` should get both executables.
> Minor fix to 'make install' to also install 'anycloud'

- avm/src/vm/event.rs
- avm/src/vm/opcode.rs
This eliminates one conditional check on each cpu opcode call, which should have a nice perf bump. If we can make the cpu opcodes infallible they can return nothing and have no conditional logic after being run at all, which should be far more significant (and closer to how they would work after a JIT is added).
> Refactor cpu opcodes to not return an optional event emission and have the emit opcode just do that itself

- .github/workflows/tests.yml
This unblocks the `??` and `?.` operators (amongst other features) that need at least Node 14. Since all major browsers support these operators now, it's safe to require and we can make the compiler a bit easier to read in certain circumstances.
> Change test suite to Node 14 and up

- bdd/spec/023_http_spec.sh
Realized that the test was failing occasionally because the last print statement wasn't being printed, and that was because of a race condition between the exit event running and stdout being flushed, so a 100ms wait should fix it.
> Eliminate the last flaky test

- compiler/src/lnntoamm/Expr.ts
- compiler/src/lnntoamm/Fn.ts
- compiler/src/lnntoamm/Operator.ts
- compiler/src/lnntoamm/Stmt.ts
- compiler/src/lnntoamm/Types.ts
- compiler/src/lnntoamm/util.ts
- compiler/temp.lnn
fixes #599 
I kept some debug output *in case* something happens but I don't expect any of them to actually print. Other than that the documentation should be pretty thorough and should in the end be more accurate than the current selection system. This system should also determine all types of values except for those that depend on the parameters of the function, which means that functions are fully type-checked (instead of only partially type-checked) before inlining, even if they're on the cold path (functions not used by any handler).
> [lnn] fn selection fix

- README.md
Apparently Github dropped the old badge URLs, but instead of breaking the image, it's just set to whatever the last result was, basically forever, which I don't understand the logic of.
> Fix CI badge URL

- avm/Cargo.lock
- avm/Cargo.toml
- avm/src/daemon/stats.rs
This is not yet a complete replacement. The CPU times for user/sys/idle/etc aren't working. Reviving that correctly may or may not matter. The centralized alan deploy service is dead and will be replaced with something within the AVM itself; whether or not that info is needed to auto-scale is TBD.
> Replace Heim with sysinfo

- avm/Cargo.lock
- avm/Cargo.toml
- avm/src/vm/http.rs
Necessary to upgrade rustls because these internal entities don't exist anymore
> Stop using rustls internals for pemfile support

- .github/workflows/tests.yml
I think I have upgraded all of the out-of-date deps that broke Windows support, but can only find out by turning Windows back on in the CI.
> Attempt to restore Windows builds

- .github/workflows/tests.yml
- bdd/spec/023_http_spec.sh
- std/http.ln
A `Content-Length` header in a GET request is invalid. Node 16 and earlier (as well as `hyper` in Rust) simply ignored the invalid header, but Node 18 is more strict. Fixed by changing the header set for GET requests to `User-Agent` with a value of `Alanlang` for now.
> Fix http requests in Node 18

- bdd/spec/023_http_spec.sh
> Restore the http post test with an http echo server 'one-liner'

- src/compile.rs
- src/lntors/function.rs
- src/program.rs
and rework microstatement generation to pass a mutable vector around for the whole function to make searching for the variable name (to get type data) possible,
> Get basic const/let statements working

- src/parse.rs
- src/program.rs
This turns the base assignable variable into a vector of VarSegment entries, which should help reduce the spread of logic on accessing properties or array locations to a singular spot and minimize the amount of nonsensical text it can parse.
Did this as a separate PR and just mushed it back into a string for now to prove that the parser change doesn't cause regressions in the test suite. (Which is true, still the same # of successful tests)
> Clean up the method and array access logic in the base assignables to be restricted to the 'Variable' branch

- src/compile.rs
- src/std/root.ln
In Alan, types are only used at compile time. There's no reflection, so we're free to even decompose the user's variables to just the parts that are necessary, if we wanted to.
And in the language design, they can only be defined at the top-level of a file, you can't define types within a function (since that would require either including a compiler within the compiled output, or some incredibly fancy way to determine at compile time all of the possible types that could be created and then used at run time and pre-build them). You also can't store them in a variable, or etc. They're "just" metadata for the compiler (and eventually intended to be non-required metadata that the compiler can create an substitute for as necessary).
So, the namespace for types vs functions and variables has …
> Constructor function naming pattern

- src/parse.rs
- src/program.rs
Also improve the error messages a bit
> Convert the baseassignable microstatement generation to a facsimile of a C-style for loop for better look-ahead handling

- src/compile.rs
- src/lntors/event.rs
- src/lntors/function.rs
- src/lntors/mod.rs
- src/parse.rs
- src/program.rs
- src/std/root.ln
- src/std/root.rs
Implements threads, unning each event handler on a separate thread and copying the data they use,
Also turns `toI8` into just `i8` for consistency and sets up a new Microstatement type, Arg, to make variable resolution work for arguments, though it doesn't guard against argument names that are valid in Alan and not in Rust.
And several bugfixes along the way.
> Implement events

- src/compile.rs
- src/program.rs
I realized that while the syntax for strings makes them multi-line by default, there was no test to demonstrate that (and the vim highlighting broke on it, so I also fixed that).
And a tiny change on some todo lines so it's more clear what it is to be done in the future.
> Add a multi-line Hello, World test

- src/compile.rs
- src/program.rs
- src/std/root.ln
- src/std/root.rs
Two of the tests for the i16 math used methods, so that's why I went with them to test the method syntax.
It currently only supports "direct" method access, not via properties, so something like `http.request("https://google.com")` would work but calling a method off of a property of a variable name would not (eg `http.request("https://google.com").response.status()` would fail to compile).
I've also set up grouping syntax (eg `(1 + 2)`) but since operators don't exist yet, that's not actually tested, yet.
> Implement basic method syntax and i16 math functions

- src/lntors/function.rs
- src/program.rs
I was thinking about how to efficiently implement some black box vector types to test with, and realized that ignoring mutability is going to significantly harm performance, so I modified the microstatement type to keep track of it and serialize to Rust appropriately.
> Keep track of mutability in microstatements, afterall

- src/lntors/event.rs
- src/lntors/function.rs
- src/std/root.ln
- src/std/root.rs
Beyond toy programs, the translation of Alan code needs to normally be pass-by-reference under the hood in Rust so variable names remain available after being used on a function call. Most developers would not expect their variable name to no longer be valid after they provided it to a function.
Further, some functions will need to be mutable references to allow mutation of a provided variable. This can make the state of your own code harder to follow since your own variables may be mutated by the functions you're calling, instead of returning a new variable with a new value, but in certain situations it is both more performant and is expected, for instance with arrays/vectors. How the clarity of mutable variables is dealt with is beyond this PR, and also probably beyond the first major …
> Convert to pass-by-reference instead of pass-by-value

- Cargo.lock
- Cargo.toml
- benches/bench.ln
- benches/map.rs
- src/lib.rs
- src/main.rs
- src/std/root.rs
The prior implementation using `Vec::append` nullified *most* of the performance benefit of parallelization because of all of the copying and resizing, likely. (It was only 10-20% faster for large vectors)
This new implementation uses some unsafe shenanigans to write directly into the output vector, and is about 4.25x faster than running sequentially on my 16-thread CPU. There's probably some contention at play since I think there's only 8 *real* cores and it's hyperthreading (or whatever AMD's equivalent is called) causes contention between them, but I might also be hitting some memory bandwidth limits, as all it's doing is multiplying values by 2, wrapping in a `Result`, and storing that in the vector.
I have been hesitant for the generated Rust code to depend on any third-party …
> Implement a faster parmap

- Cargo.lock
- Cargo.toml
- src/compile.rs
This took a lot longer than I expected (when attempting to keep the compilation time at least somewhat close to what it was before) because [`wgpu`](https://wgpu.rs), the library I am interested in using in the transpilation, takes >30sec to compile on my machine, and doing that for every single test is madness.
So after digging into how cargo's build cache works (terribly, btw), I'm making a singular project and serializing compilation through it via a lockfile, which isn't great, but at least the test suite finishes within a minute, still.
> Compile rust transpile as cargo projects

- .github/workflows/bench.yml
- .github/workflows/rust.yml
- src/compile.rs
- src/std/root.ln
- src/std/root.rs
Currently just confirming that the GPU struct actually builds correctly. Once there's some real usage of it the Debug printing of this type will go away and it'll be wholly opaque in the language
> Create the GPU type and necessary functions

- src/compile.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program.rs
- src/std/root.ln
I realized that I wanted to implement the basic GPU `run` function by passing in a type that has the wgsl shader code as a string and an array of arrays of GPU buffers (to represent the group and binding fields for mutable memory) that I could then build the better abstractions on top of, but that it was impossible because structs and arrays don't really exist, yet.
This PR gets structs working. It also partially implements arrays and the bare minimum of bool and property access to get another test working. I really need to clean up the property/method/etc logic into a properly recursive function instead of the spaghetti I have right now, but I wanted to reserve that refactor for later (both because I want to get a GPGPU benchmark working ASAP, regardless of the quality of that code …
> Implement compound types (structs), and the bare minimum of property access and booleans to get another test working

- benches/bench.ln
Now that I'm self-hosting the github actions runs so I can use a GPU, I can also increase the RAM usage of the benchmark to get a better performance boost measurement for large arrays.
> Increase the benchmark size

- benches/bench.ln
- benches/map.rs
- src/compile.rs
- src/std/root.ln
- src/std/root.rs
I had to make some modifications to handle very large arrays. Surprisingly the default limit for buffers is just 256MB. I changed it from the default to whatever the limits are for the hardware/OS combo, instead and I got ~2GB per buffer instead. This still meant my 1 billion 32-bit integers buffer was too large, so the benchmark has suffered some complexity.
I think I can use the limits object to bolt on some safety to the API, but the fact that wgpu defaults to `panic!` so much makes me uneasy. But perhaps that is impossible to avoid with GPUs right now?
> Add some GPGPU benchmarking

- src/compile.rs
- src/program.rs
I am *very* surprised that I can't debug print an error safely.
> Restore the totally broken statement test by preventing a crash in error handling

- src/compile.rs
- src/lntors/function.rs
- src/program.rs
- src/std/root.ln
Before moving too far forward on the hard stuff, getting the string type to match the conventions outlined in RFC 023: namely, all intrinsic types are lowercase and the constructor function name is simply the type name.
> Make the string type match the intrinsic conventions

- src/parse.rs
- src/program.rs
- src/std/root.ln
So the new type system has compile-time functions to generate types, or pull in specified files as strings, or etc, and itself has a very limited type system to support it.
I realized that having those types be 100% undocumented in the Alan source code would just be too magical, so I've added a `ctype` syntax to declare them in the root scope to make it clearer where they come from. They can't be created or altered, so the compiler will just be checking that the exact set expected has been specified and that there are no `ctype`s that it doesn't know, which is an immediate compiler error.
> Add a 'ctype' concept

- src/parse.rs
- src/program.rs
- src/std/root.ln
Also in this PR is a fix to the `ctype`s. I realized that they conceptually *need* to be exported to all contexts so that they can be used when creating new types.
And another small bit is fixing a bug where attempting to look up functions and types inside of the root scope can cause the compiler to crash, rather than provide a sane error message. No release would ever have to worry about this, but it does make development more difficult when this crashing causes the test suite to spin forever instead of fail with an error message.
> Start implementation for representing type operators

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/compile.rs
It's been a bit annoying to have to check the test results on all branches that there have been no regressions in the test suite when run, so this PR ignores the things that are still unimplemented.
However, I don't want the badge on the README to turn green when the language is still very broken, so I have also added a bit of logic to the workflow to *hopefully* force it to run the ignored tests on `main` so the badge remains red. We'll see soon!
> Ignore unimplemented tests

- .github/workflows/rust.yml
I realized after actually running the test command on `main` that it's only running the ignored tests, not running all of them, and then realized that I needed a different flag. Tested locally. It *should* work, but I won't know until this is merged.
> Run all tests on main

- benches/bench.ln
- benches/map.rs
- src/compile.rs
- src/parse.rs
- src/std/root.ln
This doesn't refactor how the source code parsing is done, but just changes the current parsing to use an arrow (`->`) for the return type to match what the future syntax will look like.
In the future, instead of having special logic in the parser for not including a return type, it will just be a type provided to the next stage of the compiler and if it isn't a `Function` type, then it'll be assumed that the type is the argument(s) and it needs to infer the return type. Anyways, just part of the refactoring work to get from here to the plan in the RFC.
> Switch to an arrow (->) for function type signatures

- src/program.rs
- src/std/root.ln
I do need to actually implement the `ctype`s in the compiler, but I'm a bit fried right now, so just putting up a missing integral type.
I'm also thinking that in that implementation I might eliminate the `binds` feature for types and port them all to `ctype`s for a stronger foundation for the type system, but I'm not entirely sure. It could still be useful to bind in native Rust types for third party libraries.
> Small PR to add the Either type as a built-in type

- src/lntors/typen.rs
- src/parse.rs
- src/program.rs
This simplification may or may not be long-term (adding `{}` could simply be a substitution with `=;`), but the extra focus will help with keeping the sprawl in the first stage of the compiler less large, at least in my head.
> Simplify type definition to just type assignment, no 'structlike' syntax

- benches/bench.ln
- benches/map.rs
- src/compile.rs
- src/lntors/function.rs
- src/parse.rs
- src/program.rs
- src/std/root.ln
While working on really building up the set of built-in types, it was determined that the greater than (`>`) and less than (`<`) operators would parse ambiguously with the generic type syntax (`<T>`). After looking around at different implementations of generics and comparing how ambiguous it is to parse (can be pretty honestly rated) and how ambiguous it would look to a developer (much more my opinion), it was determined that [Julia's generics](https://docs.julialang.org/en/v1/manual/types/#Parametric-Types) would win out, where it uses curly braces (`{T}`). Since the generic syntax can *only* follow a type name, it has no ambiguities while parsing, and it is *similar* to `<T>` in terms of standing out. A quick review of why the other syntaxes were dropped:
* Parens `(T)` (used by …
> Declare more ctypes and modify the generic syntax after ambiguity detected

- src/std/root.rs
This is *probably* already happening most of the time, but since these functions are primarily the implementation of built-in operators, it feels like a good idea to make sure they are inlined.
> Inline most of the root functions

- src/lntors/typen.rs
- src/program.rs
This implements type statement parsing into a `CType` tree on the `withoperatorslist` syntax group. It's not really used, yet, so there's probably parts that aren't implemented correctly, but this is a significant step along the way of having the new type system implemented.
> Implement type statement parsing

- src/lntors/typen.rs
- src/program.rs
Now that the CType is more fully fleshed out, we don't need the old Type type anymore (and it is getting in the way of some of the legibility of the codebase) so it's dropped in favor of using CType everywhere for all type declarations.
> Drop the 'Type' type

- src/compile.rs
- src/lntors/typen.rs
- src/program.rs
- src/std/root.ln
Something something neitzsche something void something something.
An empty group `()` is the `void` type, with `void` being an alias for it, which is represented as the `CType::Void` enum internally and then translated back into `()` on the Rust side.
> Implement the void type

- src/program.rs
- src/std/root.ln
These types don't work, yet, since proper parsing of generics isn't done. (They are literally types named `Maybe{T}` and `Fallible{T}` instead of `Maybe` and `Fallible` with a singular generic argument.)
I have a better idea of how to translate these types to Rust, though, so that's good. :)
> Add the definitions for the Maybe and Fallible types, and fix up a bit of the CType setup to get it to parse them correctly

- src/lntors/function.rs
- src/lntors/typen.rs
- src/program.rs
- src/std/root.ln
This is a pretty massive refactoring of the internals of the type system, switching large chunks of it from being stringly-typed to properly typed with CType trees.
Now generic type definitions work as you'd expect them to and higher-order functions *properly* check that the function being passed to it actually works!
> Properly implement generic types and function types

- src/compile.rs
- src/lntors/function.rs
- src/parse.rs
- src/program.rs
After realizing the possibility, this PR implements automatic type constructor and accessor functions, using the relevant type or field names as the function names. Tested with a basic struct-like type, will add/revive more tests, and will rip out the `new` keyword and the object literal syntax path, but I wanted to get this up and merged before the end of today. :)
> Implement automatic type constructor and accessor functions

- src/compile.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program.rs
This syntax technically is only necessary for constructing an empty array, but it should work for any number of arguments passed to it.
Fixing this revealed several bugs in different parts of the codebase, which I fixed along the way.
> Fix array constructor function syntax

- Cargo.lock
- src/compile.rs
- src/std/root.ln
- src/std/root.rs
Simple change that gets `get_or_exit` working with the new Either type. The old Result-based approach will be deleted eventually.
> 'get_or_exit' working

- src/compile.rs
- src/lntors/typen.rs
- src/program.rs
- src/std/root.ln
- src/std/root.rs
This PR implements most of the string operators (skipping regex matching for now) and implements the negate function, but doesn't bind it to an operator, yet. Also implements `Min{A, B}`, `Max{A, B}`, and `Neg{A}` type functions since they were missed earlier.
A few bugs/not-yet-implemented things were found during this:
1. If the input and output types of a function is being defined for the first time, their constructor and accessor functions are not created. Added a hack to get that working for the return type only for now, but it's making a lot of bad assumptions and really ought to be centralized in the `CType` construction.
2. Operators are index *only* on their string representation internally, which was fine when there was basically only infix operators because I decided that …
> Implement most of the string operators and partially implement negation

- src/compile.rs
- src/program.rs
- src/std/root.ln
- src/std/root.rs
Also need to create the array type to get the constructor and accessors with the array literal notation. Really need to clean that up.
The lack of proper generic functions and/or interface functions is starting to impact the root scope more regularly. Should dig into that soon-ish.
> Implement more array functionality

- benches/bench.ln
- benches/map.rs
- src/compile.rs
- src/parse.rs
- src/program.rs
This has been a lower priority task, but finally implemented it. Still on the list for numbers: integer binary, octal, and hexadecimal, and float scientific notation.
> Put underscores in numbers for easier reading

- src/compile.rs
- src/parse.rs
They only support being positive numbers, since they're usually used in conjunction with the actual byte representation. I can probably support other kinds if necessary, but will avoid unless someone asks for it.
> Implement the other integer syntaxes (binary, octal, hexadecimal)

- .github/workflows/autopublish.yml
I missed this in the last PR. There's no way to test it without merging, though, so we'll see if it works on the other side.
> Update the autopublish's repository-dispatch action

- Cargo.lock
- Cargo.toml
- src/compile.rs
I couldn't run the test suite on my new RISC-V SBC because the jitter I added wasn't good enough to fake file locking. So rather than fake it, this PR simplifies things and uses the `fs2` library to use real file locking supported by the OS. This has the added benefit of speeding up the test suite a little bit, too. :)
> Switch to proper OS-level file locking during compilation

- Cargo.lock
- src/compile.rs
- src/std/root.rs
While working with the new RISC-V SBC, I ran into gpu-related problems. I have not yet resolved them, but along the way I updated to the latest version of `wgpu`, added `wgpu`'s tracing support (eventually will make that a build option, but for now it's just on by default), and figured out that I was choosing an adapter in an incorrect way (not considering whether or not the driver even has everything necessary to support WebGPU; I thought they just wouldn't return those options, but apparently you're allowed to use them if you know what you're doing and avoid the parts of the WebGPU spec that they're not compliant with).
So I still consider it a bit of a win on this front. I do hope to get it actually running GPGPU logic on that SBC, though, but it's a lower priority.
> Rework adapter selection

- Cargo.lock
- src/compile.rs
- src/std/root.rs
Working around a bug in `copy_buffer_to_buffer` by including `MAP_WRITE` on the "normal" buffer type
> Upgrade `wgpu` to `0.20.0` for real

- src/compile.rs
While working I noticed that three test files were surviving past the test suite run, and realized why, so I fixed it.
> Cleanup after compiler error checks

- src/std/root.rs
So the way it was working before would create 5 parallel tasks for an array of length 4. It worked in most of the drivers because they just *ignored* an out-of-bounds memory access, while the Raspberry Pi driver, for whatever reason (but good for me), instead does the modulus of the index into the array of memory, so the 5th access wrapped around to the first index and then performed 2 * 4 = 8 to store that into memory.
This fixes that, which fixes things on the Pi, and potentially improves performance (in case the GPU was entering some sort of error path on the other machines and then needing to recover from that) but I have zero evidence on that either way.
> Fix an off-by-one error in the workgroup creation caught by the Raspberry Pi

- .github/workflows/bench.yml
- .github/workflows/rust.yml
- benches/map.rs
Now that I have a little Intel NUC to use for testing Windows, I manually tested and noticed a small problem with the benchmarks. This should fix that and also enable testing with it. Since I have only one Windows machine, I have also trimmed the work done on Windows vs Linux to try and reduce an increase in latency. I have also forced the normal testing path to use Linux so it doesn't accidentally clog up the Windows machine's queue.
> Fix benchmarks on windows

- .github/workflows/bench.yml
- .github/workflows/rust.yml
I just got a used Mac Mini (x86-64, only a dual core Intel i5) so now I can do some validation that things work on MacOS, too.
I can spot check from time-to-time with my wife's M2 MacBook, but I'm not going to set up a runner on that.
> Add testing for MacOS

- Cargo.lock
- benches/map.rs
- src/compile.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/parse.rs
- src/program/ctype.rs
- src/program/fnkind.rs
- src/program/function.rs
- src/program/import.rs
- src/program/microstatement.rs
- src/program/program.rs
- src/program/scope.rs
- src/std/root.ln
I'm not 100% liking this result, and since I've been working on it so long it's accumulated other random things, like improvements to the rust library updating logic, that probably should have been separate PRs, but I didn't want to do the work to disentangle it.
There's still some string-based typing in the depths of this codebase, and since I needed to change that string-based typing I touched a lot more files than I *should* have, but it is working and working faster than before.
Resolves #748
> Implement generic functions (and random cleanup along the way)

- .github/workflows/bench.yml
- .github/workflows/rust.yml
This gets the Raspberry Pi 5 involved in the CI. There's no RISC-V support for Github's Actions runner because there's no RISC-V support for .NET, which surprisingly is what the Actions runner is written in, so I'm not yet sure how I'm gonna involve my RISC-V SBC in the testing, yet.
> Set up ARM64 testing

- Cargo.lock
- src/compile.rs
- src/program/ctype.rs
- src/std/root.ln
A minor change adjusting the precedence of the buffer and group operators, as well as adding some logic to handle groups a bit better within the buffer type (though on this, I am thinking of having a "strip groups" helper method that I use everywhere rather than dealing with them piecemeal like this).
While the Generic Type Function syntax is what everything is going to be internally, I want to push the Typescript-style type syntax as the standard way to write these things because I think it's more directly legible with the symbols interspersed with type names.
> Buffer type syntax improvements

- src/parse.rs
- src/program/program.rs
Some groundwork for interfaces (but not implementing them, yet). With Alan v0.2, there's no distinction between properties and functions. Properties are just functions that return the sub-type for you. On top of that, with operators now only allowed to bind to a single function name, a special interface line type for operators is no longer necessary. This means that now interface lines are just function names and call signatures, which has been converted into *any* type you want, so a lot of special parsing logic can also disappear.
> Simplify the planned interface design

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/program/function.rs
- src/program/microstatement.rs
- src/program/program.rs
- src/std/root.ln
- src/std/root.rs
This lets me finally start cleaning up a lot of the duplication within the root scope, and makes `map` possible as a method call.
There are still some corner cases:
* Because of shortcuts taken, functions passed by name into `map` always resolves to the first definition of that function, so for now I just re-ordered the `string` constructor functions to work around this.
* Since interfaces don't exist yet, it's treating all generic type names as if they're bound to an implicit `Any` interface. Once I have interfaces, I want that binding to be explicit and if there is no binding it should refuse to infer the generic type and require it to be defined when you call the generic function.
* Since it's all implict `Any`, it's not doing any constraint checking on what it infers beyond just …
> Implement generic type inference

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/program/microstatement.rs
- src/program/program.rs
- src/program/scope.rs
- src/std/root.ln
- src/std/root.rs
While working on adding more array methods, the limitations of the temporary function dispatch logic I had were preventing these new functions to actually be useable, because the correct function was not being selected when multiple had the same name *in some situations.*
This PR improves on this a lot (but not perfectly; it's only matching one statement at a time, so it may fail if it needs to cross multiple statement boundaries. I need to do a lot of reworking to resolve that), getting the `closures_by_name` test to *actually* work, rather than me cheating by reordering the function definitions, and implementing `filter`, `reduce`, and more array functions.
> Better function dispatch and more array methods

- benches/bench.ln
- benches/map.rs
- src/compile/integration_tests.rs
- src/compile/mod.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/parse.rs
- src/program/ctype.rs
- src/program/program.rs
- src/std/root.ln
- src/std/root.rs
This PR was focused on cleaning up a lot of various TODOs. Part of that made it clear that you couldn't infer the length of a buffer type with type inference, so a generic buffer length function wouldn't work. This resolves that at the same time.
> TODO cleanup

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/program/ctype.rs
- src/program/microstatement.rs
- src/program/program.rs
- src/std/root.ln
- src/std/root.rs
This one took a while to do because it uncovered issues with the type inference as written; it was accepting garbage because I had blurred two different ways of inferring it in my head to resolve the `AnyOf` type, and it only worked accidentally before.
It also took some time because the way it was constructing an array (equivalent to buffers in Alan/JS/etc) in Rust was incorrect and I was getting really weird Rust compilation errors about fn items instead of fn pointers due to that. (Which might point at a bug in the Rust compiler, because it apparently had no problem creating an array of mutable pointers to constant integers, which is nonsensical.)
I realized that I had forgotten to create a task to make sure that *most* of the Array methods are also implemented for Buffers, and that's …
> Implement map for the Buffer type

- src/compile/integration_tests.rs
- src/std/root.ln
- src/std/root.rs
This went much more smoothly, likely thanks to the work on the prior PR.
Also nice to note that `Buffer{string, 2}` is equivalent to `string[2]` and that you can use that latter format wrapped in `{}` for constructor function usage. That's what's *supposed* to happen, but it's nice that it's working correctly even for types I hadn't tested it on, yet. :)
> Implement Buffer join

- src/lntors/function.rs
- src/program/ctype.rs
- src/std/root.ln
- src/std/root.rs
If I only cared about the buffer length, this would be a bad PR because it's much large now than before, but now it's possible to use resolved Int or Float types as values within the code. It's unfortunately jumping through a useless function at the moment, but hopefully that can be eliminated in the future.
But in any case, this is particularly useful for any code that needs to use a generic-derived integer or float type as a value to accomplish what's necessary. Here returning the length of a buffer by just inspecting the type information, but it could potentially be used for matrix math or what-have-you, and before it required writing a Rust function to get at this information, and now it's pure Alan code.
> Implement the Buffer len function with a type system hat-trick

- src/compile/integration_tests.rs
- src/std/root.ln
- src/std/root.rs
While looking at the closely related `find` and `index` functions, I realized that there was some missing functionality with `has` (and `index`) -- the ability to provide a checking function instead of an exact match on the value, letting you use your own logic to decide if the array or buffer has what you want.
> Implement a variant of has that accepts a checking function

- src/compile/integration_tests.rs
- src/std/root.ln
- src/std/root.rs
Alan v0.2 doesn't really need these functions for the optional and fallible types. You can just `Maybe(val)` to be equivalent to `some(val)`, `Maybe{myType}(void)` to be equivalent to `none` (a bit more awkward, type inference should eventually support `Maybe(void)` for `none`), `Fallible(val)` for `ok(val)` and `Fallible{myType}(errorVal)` for `err(errorVal)` (again, type inference may help here). And the `Maybe` and `Fallible` "functions" could be bound to `?` and `!` postfix operators to turn that into just `val?`, `void?` (assuming inference works as desired), `val!`, and `errorVal!` (again assuming inference works as desired) which is even shorter.
At the same time, many languages have a different meaning for `some`, as an array method for determining if any of the elements of the …
> Drop ok, err, some (both kinds), none from language

- src/compile/integration_tests.rs
- src/std/root.ln
After thinking about it, there's no agreed upon set of operators for string manipulation like there is for arithmetic, and most languages are moving away from the few that gained some traction (eg `+`) and are moving towards string templating, instead.
So this removes almost all of them. I am still keeping `#` as a `len` operator for now since it applies to strings, buffers, arrays, and potentially other types, and I recall Perl having an operator like this. But it may also get dropped in the future.
> Drop most string operators

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/std/root.ln
Also fixed some errors in the rust codegen layer (it's still really hacky, but okay for now)
> Implement 'getOr' for any Either-based type. Depends on the 'getOr' for the Maybe type to work.

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/std/root.ln
- src/std/root.rs
In order to properly infer `A + B` in the type system, `Add` needed to be able to be lazily evaluated, so a *lot* of types were added to the `CType` enum in order to get this working. Also, I forgot to add `get` support for Buffers, and probably a few other things.
> Get Array and Buffer 'concat' working... by a major update to the type system

- src/std/root.ln
- src/std/root.rs
In the last PR I somehow forgot that I had already implemented `concat` for Arrays, so I implemented it again. This removes the new duplicate implementation.
> Remove redundant 'concat' implementation

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/program/microstatement.rs
Resolves #752
Doesn't implement move semantics, so returning closures probably doesn't work yet. But creating a closure to pass to `map` works just fine.
> Implement closures

- src/compile/integration_tests.rs
- src/lntors/typen.rs
- src/std/root.ln
- src/std/root.rs
Resolves #753
Mostly. The `hash` function has some serious issues for more complex types that need to be addressed. Left comments on this for now. It may become an automatic `Derived` function for efficiency's sake, walking the `CType` tree to figure out what operations to perform.
`clone` *should* be 100% done, assuming that all complex types have `#[derive(Clone)]` defined, which the ones generated by the compiler should be.
> Implement 'hash' and 'clone' functions

- src/compile/integration_tests.rs
- src/std/root.ln
- src/std/root.rs
As noted in one of the comments, the type system can't currently handle repeating buffers an arbitrary number of times because the value is a runtime value. The type system needs to be improved to be able to distinguish the literal `3` from a variable `three` that may or may not have the value `3` inside of it before this can be improved.
Then we can have both the current implementation for runtime variables, which *has* to convert into an array to have a static type, and a new implementation for static values that can convert into a buffer on the other side, as well.
> Array and Buffer (kinda) 'repeat' implemented

- src/parse.rs
- src/program/microstatement.rs
- src/std/root.ln
This sets up the language to just have `=` be an operator for `set`. Work needs to be done in the lower layer of the language to be primarily reference-based and insert variable assignments as necessary for Rust's ownership model, but that will happen later.
> Drop special assignment syntax in the language

- src/compile/integration_tests.rs
- src/program/function.rs
- src/program/microstatement.rs
- src/std/root.ln
- src/std/root.rs
This only has the bound `cond` function that executes either the `true` or the `false` branch working.
The wrapper function that accepts only a `true` branch and returns a `Maybe{T}` doesn't work yet because there's a bug in the `Scope` implementation that I have finally figured out is much larger than I anticipated. I need to potentially rework how `Scope` works to a large degree in order to get Rust to accept it. (Creating a child scope actually creates two scopes, one that is registered in the scope tree and the one that is returned; mutating the returned one doesn't affect the one in the tree and so adding arguments to the scope as callable functions does not work.)
That will be a different PR because it would be confusing, otherwise.
> Implement 'cond' for basic conditionals

- src/compile/integration_tests.rs
- src/std/root.ln
- src/std/root.rs
Resolves #755.
The `exists{T}` function for `Maybe{T}` types returns a boolean on whether or not the `Maybe` has a `T` value inside or not. With it we can accomplish something similar to the `is{T}` concept for `Either` types.
`myEitherType.is{mySubtype}` was the goal, but now we get `myEitherType.mySubtype.exists`. Still pretty legible, not as "English-like" as the desired syntax.
The `void{T}` function that consumes any input type and returns a `void` isn't really related to this, but I decided to implement it at the same time because why not? It is not *currently* useful, but I am currently leaning towards *any* statement that doesn't have a resulting value of `void` is a compilation error as the value has not been consumed. This would be an easy way to enforce handling `Fallible` …
> Implement `exists{T}` and `void{T}` functions

- benches/bench.ln
- src/lntors/function.rs
- src/program/microstatement.rs
- src/std/root.rs
This fixes an issue with closures actually using variables from the outer scope by making sure they're available as owned values within the closure. This is a super trivial implementation that just `clone`s everything from the outer scope, but it works, and appears to have the unused `clone`s deleted during LLVMs optimization passes (probably just dropping all unused variables in their entirety?) "If it's stupid but it works..."
> Closure functions actually enclose outer-scope variables

- src/std/root.ln
- src/std/root.rs
While planning out how to generate the shader code from Alan code, I realized that it might be possible to do it in pure Alan code, but I would need to have a few things set up in the language. I also realized an issue with the GPGPU code that hasn't shown up only because I've only really tested the `GPGPU_new_easy` function. This is the first of a few PRs to get the groundwork done.
The issue with GPGPU code is that the codegen for Alan right now assumes that *everything* can be `clone`d, and `wgpu::Buffer` cannot, so this PR has changed the `GBuffer` binding of `wgpu::Buffer` to instead bind `Rc<wgpu::Buffer>` to give us cloning capabilities.
I also realized that shader generation depends on not only constructing a sequence of operations that will return some value for each global id …
> Buffer Rc and id

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/program/fnkind.rs
- src/program/function.rs
- src/program/scope.rs
- src/std/root.ln
- src/std/root.rs
I also had to fix some bugs with type resolution to get this working. There was a more fundamental issue with type resolution that was fixed by also registering the ctype `to_callable_string` as a typename in the scope.
> Get basic reassignment working and implement type 'tagging'

- src/compile/integration_tests.rs
- src/compile/mod.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/parse.rs
- src/program/ctype.rs
- src/std/root.ln
- src/std/root.rs
This is part of #759 but does not yet implement all of it.
There is a blocking bug that was discovered that needs to be resolved (and should be a different PR as this one is already really long-in-the-tooth): The function resolution logic is resolving the wrong `store` function, so I temporarily named it `save` in this PR.
> Implement GPU Types and Methods, and implement a new hello_gpu example using it

- src/compile/integration_tests.rs
- src/program/scope.rs
- src/std/root.ln
So the reason why my custom `store` function wasn't being used is because the generic function `store{T}(a: T, b: T) -> T` matches *all* types when the stored value is the same type as the original value, and the way `resolve_function` worked before (because the borrow checker made that the easiest way to implement it), it would first see if any generic function can resolve for the desired function and use that, then if not, it would check if there's a "normal" function that would do. This worked most of the time because there was never a generic function that also matched a "normal" function within the codebase, yet, but if there's ever a match for both generic and normal, the normal function, which had to be handwritten by the developer, should be preferred, so this PR reverses that and …
> Prefer normal functions if one is defined

- src/compile/integration_tests.rs
- src/std/root.ln
I realized that the single-argument `gFor` would be more intuitive to also return access only to the `x` value, instead of a vector.
> Minor `gFor` update

- src/compile/integration_tests.rs
- src/std/root.ln
Also implementing auto-casting of `add` and `mul` when mixing convertible types, so you don't have to write `+ 1.gi32` and can instead just write `+ 1`. Currently implemented with generics to convert any type as needed, but may switch that to just `i64` and `f64` where appropriate to prevent auto-casting of GPU types into each other in potentially unpredictable ways.
> Implement GPU `add` and GPU vector `.i`, `.j`, `.k`, and `.l` aliases

- Cargo.toml
Since the `bin` and `lib` paths in `cargo test` run *exactly the same test suite*. CI has always run the test twice in a row.
This hasn't really been a big deal for my x86 Linux machines, but the little ARM machine has always slowed down the CI job, and with more and more GPU-oriented tests being added, it will only get worse more quickly than before, so I finally felt the need to figure out how to stop the duplicate test runs.
> Only test once

- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/std/root.ln
- src/std/root.rs
This feels more "Alan" to me (there's no special function to make a void-value Either type anymore, just call the normal constructor function with no values), simplifies the codebase a bit, and fixes a bug in the rust codegen.
> Better enum construction for void type values

- src/compile/integration_tests.rs
- src/parse.rs
Discovered while writing the documentation on primitive types. :)
> Fix negative exponents in scientific notation

- src/std/root.ln
While writing the documentation I realized that error construction was inconsistent with other types because the constructor function name did not match the type name.
> Make error construction consistent with other types

- benches/bench.ln
- src/compile/integration_tests.rs
- src/std/root.ln
- src/std/root.rs
I also realized while writing the documentation that there is no reason why the conditional function can't be named `if` in Alan, and that makes it easier to understand when you want to extend conditional behavior.
> Rename `cond` to `if`

- src/program/microstatement.rs
- src/std/root.ln
I noticed that the negation precedence was all wrong (it should be the highest precedence so it attaches its negation to the nearest variable only).
I also removed a TODO that was already done but the notice was forgotten about.
> Fix negation precedence

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/program/ctype.rs
Resolves #836
The entirety of the derived function generation inside of `lntors` definitely needs reworking. It's a rat's nest...
> Implement auto-wrapping for sum type reassignment

- src/lntors/function.rs
- src/lntors/typen.rs
- src/parse.rs
- src/program/ctype.rs
- src/program/function.rs
- src/program/microstatement.rs
- src/program/scope.rs
- src/std/root.ln
This actually *simplifies* a lot of code by working this way. There will be a follow-up PR for function binding, hopefully tomorrow.
> Implement type binding via generic types instead of special syntax

- src/program/constn.rs
- src/program/ctype.rs
- src/program/function.rs
- src/program/import.rs
- src/program/microstatement.rs
- src/program/operatormapping.rs
- src/program/scope.rs
- src/program/typeoperatormapping.rs
This PR doesn't change any of the logic in the microstatements to fix known bugs with it, but simply refactors things to use full ownership. A lot of weird contortion in there will be reduced to this simpler kind of contortion in a follow-up PR.
This is to deal with an issue with the borrow checker being unable to recognize that a mutable reference has "died" at the end of a function call because it's single-threaded code that can't have given that reference to another thread to then mutate whatever it feels like. It feels like it'd be really nice to be able to say that the mutable reference doesn't live past the function call in question, but I can't figure out how to do that, so instead I'm passing ownership of the `Scope` to the function that mutates it, and then it passes back both …
> Refactor all mutations of a Scope to be done with full ownership rather than mutable references

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/program/ctype.rs
- src/program/function.rs
- src/program/microstatement.rs
- src/program/scope.rs
- src/std/root.ln
Part of #756 but only just barely working. This type is uncovering a *lot* of bugs in the compiler. I had to do the scope ownership reworking in order to even make this possible (by then also reworking how child scopes are merged into the parent scope and making sure this is never skipped out on).
> Initial Tree type implementation

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/lntors/typen.rs
- src/std/root.ln
Part of #759
This implements [comparison operators](https://www.w3.org/TR/WGSL/#comparison-expr) and the [if statement](https://www.w3.org/TR/WGSL/#if-statement). The `if` statement can still only be used in functional style since the conditional syntactic sugar hasn't been implemented yet, but this is a pretty big step forward!
> Implement GPU comparisons and if functionality

- src/parse.rs
- src/program/ctype.rs
- src/program/function.rs
- src/program/scope.rs
- src/std/root.ln
This gets the `.` working correctly for the type system. There's no method syntax for types like I was originally thinking of adding support for, but there is a way to access "properties" of types to get at subtype definitions. Eg, a field name for a tuple to get the sub-type, or a number to get the Nth tuple or either sub-type.
This is used in some of the generic functions for the GPU types to get at the `typeName` tag to then use it within the function itself, reducing redundancy and potential sources of error.
This also allows a kind of compile-time type introspection system to probe the structure of the type that was given to you in a generic function, which could be useful without needing to worry about runtime exploits injecting into a "live" reflection system.
> Add the Prop{T, P} type function and use it for some GPGPU functions

- src/program/ctype.rs
I changed my mind on this. It can be useful to be able to automatically "take apart" a field by numeric index, especially if you don't know what the field name is where you need the underlying type to the field.
> Allow numeric access to field types

- src/lntors/function.rs
- src/lntors/typen.rs
- src/parse.rs
- src/program/ctype.rs
- src/program/microstatement.rs
- src/program/scope.rs
- src/std/root.ln
I realized that I could just represent the "bare type" binding with an array of zero elements, so this reduces the number of type functions to learn.
> Consolidate the Binds{T} and BindsGeneric{T, ...} into one ctype

- src/parse.rs
I somehow missed this in the function binding PR
> Remove no longer used piece of the parser

- src/program/ctype.rs
- src/program/scope.rs
- src/std/root.ln
- src/std/root.rs
This PR adds `Mut{T}` and the ability to use static constants in bindings. The second piece is used by the PR, but the first can't yet because of issues with the codegen layer basically wrapping with immutable references.
> Add Mut{T} and support for static literals in bindings

- src/compile/integration_tests.rs
- src/lntors/function.rs
- src/program/argkind.rs
- src/program/ctype.rs
- src/program/function.rs
- src/program/microstatement.rs
- src/program/mod.rs
- src/program/scope.rs
- src/std/root.ln
- src/std/root.rs
I wanted to hide this, but I think making it clear that a function is going to mutate a variable that was passed to it is worthwhile to have in the language.
I then use this to improve the bindings into Rust (and yay, I no longer have to make every function take `&mut` for everything!)
> Add mutable references to the language

- src/compile/integration_tests.rs
- src/program/function.rs
- src/program/microstatement.rs
I realized this morning that the bug I saw last night wrt the `Fallible{T}` test confusingly still requiring the return type annotation was due to an issue with proper type resolution for inferred return types.
I need to construct all of the type's functions *after* inference is complete, not before. And at the same time I was able to eliminate some hacky code that was doing it, so it should now be possible (at least for the type system) for a function to return a function without causing the compiler to barf.
> Fix the bug blocking the Fallible test from eliminating the return type annotation, removing some hackery and properly resolving return types

- alan/src/program/ctype.rs
- alan/src/program/function.rs
- alan/src/program/scope.rs
- alan/src/std/root.ln
This puts the function evaluation order back in line with Alan v0.1, which is also an easier-to-understand model, where definition order produces the priority when multiple functions could be dispatched to.
So now you write your generic versions first and the specialized versions afterwards, effectively as exceptions to the rule. And so it's *possible* to override a broad default function with a special one for your own use-case and have it actually work, rather than magically require the broad (probably built-in) function to be defined *after* your own code, despite it living in the root scope.
> Fix function evaluation order

- .github/workflows/node.yml
- .gitignore
- alan_std.js
- alan_std.test.js
- package.json
This has to be separate from the binding of the i16 arithmetic operations into the language because the stdlib is installed via npm from whatever's on `main` (for now).
> Implement js stdlib testing and the i16 arithmetic

- alan/src/compile/integration_tests.rs
- alan/src/std/root.ln
I will probably follow this up removing a hack from the root scope and shoving it into an appropriately named JS stdlib function.
> Bind the JS u8 bitwise and arithmetic operations

- alan_std.js
- alan_std.test.js
Unfortunately, because Javascript passes primitive types by value instead of by reference, there's no good way to have custom user functions that mutate primitives, which Alan allows, so I have to have these wrapper classes for numbers instead. :(
> Create a set of JS integer classes

- alan/benches/buffer_shader_timings.ln
I realized the mistake after I tried to run the earlier version on MacOS and it *crashed* the machine (!!!) and then realized what I did wrong when I actually printed the buffer once it was in RAM and saw the garbage that was produced, particularly with the first few, which didn't change the buffer at all.
I was accidentally setting the `yMax` to `0`, which Vulkan and DirectX decide this means "don't run the shader at all" but Metal decides "run the shader on ALL of the GPU memory address space (afaict) until it messes with something it shouldn't and blows up the machine.
This fixes the bug here explicitly, but I need to decide what to do if you call `gFor` with invalid arguments ("correct" the `0` to `1`? `panic!` the program? make `gFor` fallible and return an error type?)
> Fix a bug in buffer_buffer_shader_timings.ln

- .github/workflows/rust.yml
- README.md
- alan/src/compile/integration_tests.rs
- alan/src/compile/mod.rs
- alan/src/lntojs/mod.rs
- alan/src/lntors/mod.rs
- alan/src/main.rs
- alan/src/program/ctype.rs
- alan/src/program/program.rs
- alan/src/program/scope.rs
Also make the environment frozen for the program on startup, which allows the test suite to run "normally" (multithreaded) because it doesn't depend on the single-threaded env type anymore.
This is in preparation for allowing imports of other source files to finally work.
> Refactor the Program type to be used as a singleton

- alan/src/compile/integration_tests.rs
- alan/src/compile/mod.rs
- alan/src/lntojs/function.rs
- alan/src/lntojs/typen.rs
- alan/src/lntors/typen.rs
- alan/src/main.rs
- alan/src/program/ctype.rs
This actually should fix a whole class of type bugs where `AnyOf` is involved, which *generally* comes from multiple function definitions with the same name being passed as an argument to a function. If a generic type is not yet constrained enough to eliminate all of the options, rather than failing outright, it just keeps the ones that work around and narrows them later, assuming some other values passed into the function call can do so.
It doesn't have any tiebreaker logic if a generic type can't be narrowed -- that's still a compilation error. I feel like that should stay the same because you don't want the code doing something seemingly at random just because some other function you weren't aware of could match and it was selected for reasons you don't know.
I did this while working …
> Fix issue with matching when the first argument is a generic function definition

- alan/src/parse.rs
- alan/src/program/scope.rs
- alan/src/std/root.ln
I realized that the root scope doesn't need to export anything since it's always included in the scope hierarchy, so I dropped the essentially useless `export`s (after a minor tweak to how the `ctype` syntax is parsed). Then I realized that the type-operator and function-operator binding can be done before any types or functions are defined, which would then let me use the operators where it makes sense to use them, so I also refactored *everything* according to that. Then I re-ordered the floating point and integer types and functions according to the new "FUI" ordering I'm going to use for tiebreaker logic in the near future. Finally I added a few more operators where it made sense to me.
> Make the root scope code more 'normal' looking

- alan/src/lntors/typen.rs
While working on other things, I noticed this typegen bug in the Rust type generation and fixed it (there's no equivalent in the JS codegen because the JS path doesn't emit types).
> Fix a Rust typegen bug

- alan/src/compile/integration_tests.rs
- alan/src/std/root.ln
- alan_std/src/lib.rs
Another relic of Alan 0.1 that doesn't really do anything right now, is difficult to support (not implemented in JS, and the implementation is broken in certain scenarios on Rust), and a distraction from what Alan 0.2 is about.
> Remove the `hash` built-in function

- alan/src/compile/integration_tests.rs
- alan/src/std/root.ln
- alan/test.ln
There are several compromises here that I want to eventually tackle.
1. The CPU side uses `f32[3]` or `f64[3]` as the type, rather than a more specialized one. Right now there's no reason to use a specialized one because CPU vector intrinsics are locked to Rust nightly, but perhaps it makes sense to create CPU-side `vec[2/3/4][f/u/i]` to match the GPU side and in preparation for when they actually do get proper acceleration?
2. I can't create a buffer of an array of `f32[3]`s and then read that back out. Much of the `GBuffer` behavior dates to before I had generics at all, and I should probably spend some time reworking it from the ground up. This means that I had to do the cross product on the GPU side and then just extract the `z` value out for checking, instead of checking against the …
> Implement the cross product for CPU and GPU

- alan/src/program/ctype.rs
- alan/src/std/root.ln
- alan/test.ln
- alan_std.js
- alan_std/src/lib.rs
I've decided to just bind the native `sort` functions from Rust and Javascript for now, but since I already put the work into implementing `swap` and because it is still useful outside of the context of in-place sorting, I'm making this PR to include it.
> Implement the 'swap' method for arrays and buffers

- alan/src/compile/integration_tests.rs
- alan/src/program/program.rs
- alan/src/std/fs.ln
This is the beginning of the first non-root standard library in Alan v0.2: `@std/fs`.
For now, only one feature is implemented: reading an entire text file into a string.
Other things will be implemented over time, but since filesystem access doesn't exist in the browser, I'm not sure if I'll devote much effort into it in the near term. This is for Advent of Code 2024.
> Implement the bare minimum for `@std/fs`: file reading support

- alan/src/std/root.ln
This appears to be an issue with type resolution that I need to do a deeper dive on, but skipping the useless wrapper function around the bound native function seems to resolve this.
> Fix calling `reduce` in Javascript when the default value is a tuple

- alan/src/lntojs/function.rs
- alan/src/lntojs/typen.rs
- alan/src/std/root.ln
This PR has two separate fixes merged together.
1. Added a new `get{T}` function for the `Maybe{T[]}` type, allowing you to try and get a value out of an array that may or may not exist. This means instead of needing to write `(arrayOfArrays[i] ?? [])[j]` you can just write `arrayOfArrays[i][j]`, which is much nicer.
2. This worked fine in Rust, but I uncovered a missing case in the JS codegen path for this, so that is also updated (and I updated the error message to include more useful information if a failure like this happens again).
> Allow chaining of nullable `get` calls and fix a bug in JS codegen for optional arrays

- alan/src/compile/integration_tests.rs
- alan/src/program/microstatement.rs
- alan/src/std/root.ln
- alan/test.ln
This fix is working around an issue with how generic types interact with the function type. Defining a function type `T -> T` *looks* like it should work just fine, but if the type `T` is resolved to is a tuple type, eg `i64, string` that becomes `i64, string -> i64, string`, where the first half of that then gets interpretted as a function with two arguments. If you instead write this generic function type as `(v: T) -> T` it becomes `(v: (i64, string)) -> i64, string` when analyzed and remains a single argument.
I'm not happy with this workaround, but I'm also not sure if ripping up a ton of the generic type resolution code to "fix" it is a good idea. (Specifically because when I did try to do that yesterday, I got caught in a quagmire of other code in the root scope failing because it …
> Fix generic type resolution when cloning structs

- .github/workflows/rust.yml
- alan/src/compile/integration_tests.rs
- alan/src/lntors/function.rs
- alan/src/std/root.ln
If you try to have two branches of an `if` function call that both try to mutate the same outer variable, that will not compile in Rust because it was implemented as closure functions that are then called, and that fails the borrow checker due to two mutable references taken "at the same time" (this is potentially true if they were passed to different threads, but not how we're using it).
So this hackery (that will eventually be formalized) rewrites back into a normal conditional statement to make this common style of code work.
> Add some hackery for conditionals where the functions are "block-like" side-effect-only functions for Rust

- alan/src/lntojs/function.rs
- alan/src/lntors/function.rs
- alan/src/program/ctype.rs
- alan/src/std/root.ln
- alan_std.js
I could have sworn I had `.0`, `.1`, etc working for buffers, but apparently not, so this implements it.
I also ran into a weird issue with sets of buffers in Javascript and realized that `Set` in Javascript only does exact object checking (eg, just comparing if the value pointer is equal) so recreating a buffer and testing it would fail because they are different buffer objects in memory. This change resolves that, as well.
> Fix direct offset access for buffers and make Set work as expected in Javascript

- alan/src/std/root.ln
Missed this in the last one because I forgot that the alan_std is loaded from `main`, not the branch by default, so it didn't actually test that path.
> Fix the GPGPU run Rust binding

- alan/src/compile/integration_tests.rs
- alan/src/program/ctype.rs
- alan/src/program/microstatement.rs
- alan/src/program/scope.rs
- alan/src/std/root.ln
- alan_std.js
- alan_std/src/lib.rs
I also improved the primitive type situation to use the version defined in the root scope (with one downside as there are a few compile-time boolean constants defined *before* the runtime boolean type is defined, and their run-time accessor functions are therefore not created, but I'll come back to that later). This improvement means in the future a change that only requires the root scope to be changed will not require a change in the compiler during testing.
> Add `run` method for an array of `GPGPU` values

- alan/src/std/root.ln
- alan_std/src/lib.rs
This has taken a lot of work. There's still something wonky on MacOS, but I don't think that needs to block this PR.
It's hard to automate testing of UI code, though, *especially* desktop UI (versus browser UI), so the test code that works with this PR is copied below (EDIT: updated the code slightly after a slight UX change):
```ln
export fn main {
print('hi');
window(fn (win: Window) = [
win.width, win.height, win.bufferWidth, win.runtime
], fn (frame: Frame) = [GPGPU("
@group(0)
@binding(0)
var<storage, read_write> pixels: array<u32>;
@group(0)
@binding(1)
var<storage, read> context: array<u32>;
@compute
@workgroup_size(1)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
let width = context[0];
let height = context[1];
let textureWidth = context[2];
let time = …
```
> Render to a Window

- alan/src/std/root.ln
The same test shader as before ported to pure Alan types, but with the "intermediate" form that I use to build the "nice" one I'd prefer people use.
Here's the ported code:
```ln
export fn main {
print('hi');
window(fn (win: Window) = [
win.width, win.height, win.bufferWidth, win.runtime
], fn (frame: Frame) {
// Little bit wonky how `frame.width` is *very* different from `frame.context[0]`.
let id = gFor(frame.width, frame.height);
let width = frame.context[0];
let height = frame.context[1];
let textureWidth = frame.context[2];
let time = frame.context[3].asF32;
let per10sec = time / 10.0;
let cycle = 2.0 * abs(per10sec - floor(per10sec) - 0.5);
let red = cycle * gf32(id.x) / gf32(width);
let green = 1.0 - red;
let blue = gf32(id.y) / gf32(height);
let alpha = 1.0;
let loc = id.x + …
```
> The GPGPU functions needed to get 'intermediate' style rendering code working

- alan_std/src/lib.rs
While debugging what's going on, I realized that the memory consumption on MacOS was growing per frame by inserting a sleep in the render loop. After spending a *lot* of time debating whether or not I should switch MacOS under-the-hood to a "traditional" vertex+fragment shader stack that copies the values out of the compute shader buffer instead of using `copy_buffer_to_texture`, I realized that there was *one* `wgpu` object that I was creating every frame that maybe shouldn't be: the surface.
I had originally avoided that because I didn't want to deal with the lifetime issues surrounding it, and it didn't seem to matter for Linux and Windows; it didn't seem to "create" anything. But perhaps on MacOS it is *actually* creating something? That would explain the weird window shadow insanity …
> Fix crash on MacOS, but improve on all platforms

- alan/src/lntors/function.rs
- alan/src/lntors/typen.rs
- alan/src/std/root.ln
- alan_std/src/lib.rs
I also made some other changes, like a GBuffer `len` producing a `gu32` moving the old `len` to `cpulen` (for the time being) (this let me get rid of `bufferWidth` from my example program, though I am keeping it around as a concept, for now, at least), and added the `min` and `max` functions (at least partially, I need to investigate if the piecewise vector behavior exists or not), etc.
The new example program is listed below:
```ln
export fn main {
print('hi');
window(fn (win: Mut{Window}) {
win.cursorInvisible;
return [
win.width, win.height, win.runtime, win.mouseX, win.mouseY
];
}, fn (frame: Frame) {
let id = frame.pixel;
let width = frame.context[0];
let height = frame.context[1];
let time = frame.context[2].asF32;
let mouseX = frame.context[3];
let mouseY = frame.context[4];
let …
```
> Mouse position and cursor visibility support

- alan/src/std/root.ln
- alan_std/src/lib.rs
This gets window transparency working. It only supports pre-multiplied transparency, though, which requires the `RGB` channels to have `A` multiplied onto them for it to work. Not difficult, but perhaps not expected that a "full bright red" is actually `127` if the alpha is `127`, and weird stuff happens if it goes above that.
I can probably have a helper function to do that for users to simulate `PostMultiplied` mode, though.
I also had to make it so the context function *is* called first in order to get the transparency flag for `X11` windows set properly. Transparency won't work at all for the browser, so I guess toggleable transparency is just a "nice to have." (I wonder why the program's running under XWayland instead of directly on Wayland, though).
> Enable window transparency

- alan_compiler/src/std/root.ln
- alan_std/src/lib.rs
- **Run an initial context function separate from the per-frame context function**
- **Update the window function binding**
> Add an `initial_context_fn` to eliminate useless work per frame

- alan_compiler/src/std/root.ln
- alan_std.js
- **Implement `runWindow` for JS**
- **Implement support functions**
- **Implement js bindings**
- **performance is lowercase in JS for some reason, breaking past conventions**
- **Wait for `document.body` to exist**
- **Fix typo in event name**
- **Fix workgroup size mangling hack**
- **Inline the buffer creation to make sure the same device instance is used to create them as the one associated with the canvas**
- **Fix typo on one buffer creation call**
- **Make the canvas actually use the real width and height, and resize appropriately**
- **This doesn't seem right, but let's see what it does**
- **Revert "This doesn't seem right, but let's see what it does"**
- **Perhaps this is the source of the rendering glitch**
- **After reviewing the Rust code, I think this is the source of the …
> Window rendering in Javascript using WebGPU

- alan_compiler/src/lntojs/function.rs
- alan_compiler/src/lntors/function.rs
- alan_compiler/src/program/ctype.rs
- alan_compiler/src/program/function.rs
- alan_compiler/src/program/microstatement.rs
- alan_compiler/src/program/scope.rs
This speeds up compilation of the `Hello, World!` app by ~33% both natively and in the browser.
That still puts it in the seconds range, which isn't great, but baby steps. :)
The majority of the time left is almost evenly split between generating Rust/JS-compatible names for types/functions and actually constructing the function objects. I'm going to dig in a bit on the former to see if I can speed that up (it's kinda crazy how long that's taking), but for the latter the only solution is to make function creation lazy, which I have been avoiding, but maybe I shouldn't?
> Eliminate many Function clones

- alan_compiler/src/program/ctype.rs
I followed the pattern in `to_functional_string` with `to_strict_string`, and the initial version was actually *slower* on average than the original that constructs a ton of temporary strings.
I was puzzled by this, but then realized that Rust was not able to turn the `CType::Infer` values I was creating at the beginning of the loop into constants, and was actually constructing those strings on each call. Because the number of these quasi-constant strings needed for `to_strict_string` was much higher, this pushed the average number of string allocations *up* instead of down.
So I used `OnceLock` to lazily create a singleton for each of these quasi-constants and *that* gave me the speedup, and I re-used this in `to_functional_string` to make that slightly faster, as well.
While rewriting …
> Faster `to_strict_string`, `accepts`, and slightly faster `to_functional_string`

- alan/src/compile/integration_tests.rs
- alan/test.ln
- alan_compiler/src/lntors/function.rs
- alan_compiler/src/lntors/typen.rs
- alan_compiler/src/std/root.ln
This took more work than I expected, because I ran into an unexpected issue with `Fallible` and `Maybe` when given an `Array` as the inner type.
This was due to both of those being based on `Either` and unlabeled types not working because you can't access their value directly (as you can't write a function call for the inner type without a name).
Now an automatic function name is added to all types via `to_callable_string` to prevent the compilation failure, though it is still impossible for a bare `Either` to work with it because that function name isn't added into the scope. I need to think some more on if/how to tackle this. Perhaps using `.0`, `.1`, etc like tuples?
> Implement `fma`

- alan/src/compile/integration_tests.rs
- alan_compiler/src/lntojs/typen.rs
- alan_compiler/src/program/ctype.rs
- alan_compiler/src/program/program.rs
- alan_compiler/src/std/root.ln
This supposedly will fail on Metal since each execution is being done in a separate workgroup and Metal doesn't provide `storageBarrier` guarantees across workgroups (despite the naming and there being a `workgroupBarrier` that should be the one constrained per workgroup) but I figured I may as well test it out with my two Apple machines and see what happens.
I may still discourage using `storageBarrier` since making a pipeline with two shaders that is guaranteed to work as expected is nearly identical in Alan instead of a big pain-in-the-butt in normal WebGPU.
Eg
```rs
[
someGpuCompute(),
storageBarrier(),
someMoreCompute()
].build.run;
```
vs
```rs
[
someGpuCompute().build,
someMoreCompute().build,
].run;
```
But if this does work, it is theoretically faster and can be used in loops of …
> Implement `storageBarrier`

- alan_compiler/src/std/root.ln
While working on documentation, I realized that this function definition can't ever actually be called (and didn't do what it was supposed to, anyways), so I deleted it. Tests passed locally.
> Remove a useless `getOrExit` function that could never be called

- alan_compiler/src/std/root.ln
While documenting the root scope, I noticed that one of the implementations of `if` for the GPU was never going to be used, so I deleted it. It was also the more complicated of the two, so this is better, anyways.
> Remove an unused GPGPU conditional function implementation

- alan/src/compile/integration_tests.rs
The `duration_print` integration test has always been a little bit flaky, I think because it's sometimes running the callback slightly *before* 100ms instead of slightly *after*, so the check for `0.1...` is failing because it's `0.09...`
Adding an extra 10ms to make this far less likely to occur.
> Try to resolve a flaky test in the test suite

- alan_compiler/src/std/root.ln
I don't have a test for this yet, so I didn't catch this mistake. I used the `gu32` type instead of the `u32` type as the generic argument for the `GBuffer` the GPU rendering type creates for the context and framebuffer buffers, which prevented it from compiling correctly.
A demo program that uses these types is included below:
```rs
export fn main {
print('hi');
window(fn (win: Mut{Window}) {
win.cursorInvisible;
win.transparent;
}, fn (win: Mut{Window}) = [
win.width, win.height, win.runtime, win.mouseX, win.mouseY
], fn (frame: Frame) {
let id = frame.pixel;
let width = frame.context[0];
let height = frame.context[1];
let time = frame.context[2].asF32;
let mouseX = frame.context[3];
let mouseY = frame.context[4];
let per10sec = time / 10.0;
let per15sec = time / 20.0;
let cycle = 2.0 * …
```
> Fix GPU rendering path

- alan_compiler/src/std/root.ln
Switching the code to generating a new variable for each intermediate value in a statement, which makes the `wgsl` code more verbose in terms of the amount of generated text, but no longer duplicates computation, so it should result in more succinct (faster) shaders.
> Implement verbose yet more succinct wgsl shader generation

- alan/benches/bench.ln
- alan/benches/buffer_shader_timings.ln
- alan/benches/map.rs
- alan/src/compile/integration_tests.rs
- alan_compiler/src/lntojs/function.rs
- alan_compiler/src/lntojs/typen.rs
- alan_compiler/src/lntors/typen.rs
- alan_compiler/src/program/ctype.rs
- alan_compiler/src/std/root.ln
- alan_std.js
- alan_std/src/lib.rs
The `GBuffer` constructor functions are now `Fallible` in case you try to allocate too much memory for a single buffer. Technically this should apply to all memory allocations, but GPU buffers have a much lower limit than "all of the RAM on the GPU", while crazy trickery in modern operating systems means you can allocate more memory than should be physically possible and the OS will swap memory around under the hood for you.
This means that you actually *do* need to pay attention to over-allocating for the GPU but don't really need to for the CPU.
In the process of doing this change, I ran into compiler bugs with Fallible being used with `Tuple` types, especially in the JS path, but also a couple on the RS path and one during the constructor function generation for any `Either`-based …
> Safer `GBuffer` (fallible if attempting to overallocate)

- alan/src/compile/mod.rs
This was discovered by a user in the Discord server. After some digging to make sure I had set `edition` correctly, I found [this issue](https://github.com/Lokathor/bytemuck/issues/306) where the conclusion is that there is a bug in earlier versions of `cargo` that are causing it to think the file is using 2024 edition, instead, when `rust-version` is declared.
So for now, the generated code will be hardwired to `bytemuck_derive` @ `1.8.1` as suggested by one of the users as a workaround. I may bump the minimum Rust version to one that doesn't have this bug later on, but this will unblock things for the time being.
> Force an older version of bytemuck_derive so earlier Rust versions still work
